// SAM3 Formelquiz — datasett
// Bygges som tre globaler: symbolKeys, decks, cards. Alle quiz-flatene
// (formelquiz, multiple-choice, mock-eksamen, formelark) leser herfra.
const symbolKeys=['π','πᵉ','α','δ','κ','β','λ','ρ','ε','θ','γ','Δ','≈','−','~','^','*','Ŷ','Ỹ','Ȳ','π*','r*','i*','φπ','φY','Lₐ','Lᵧ','P*','Sₜ','Bₜ','SPU'];

const decks=[{id:'all',title:'Alle formler',desc:'Blandet eksamensøving'},{id:'regnskap',title:'Nasjonalregnskap',desc:'BNP, sparing og åpen økonomi'},{id:'vekst',title:'Vekst og Solow/Romer',desc:'Produksjon, kapital og steady state'},{id:'arbeid',title:'Arbeidsmarked',desc:'Ledighet, strømmer og Okun'},{id:'inflasjon',title:'Inflasjon og pengepolitikk',desc:'Fisher, Phillips og kvantitetsteori'},{id:'kortsikt',title:'Kortsiktig makro',desc:'IS-MP, Phillips, AD-AS og multiplikator'},{id:'apen',title:'Åpen økonomi',desc:'Valuta, realkurs og UIP'},{id:'finans',title:'Finanspolitikk',desc:'Gjeld, handlingsregel og budsjett'}];

const cards=[
  // === Nasjonalregnskap ===
  {id:'bnp',deck:'regnskap',topic:'Nasjonalregnskap',q:'Hvilke komponenter består BNP av etter utgiftsmetoden?',hint:'Fyll inn de fire etterspørselskomponentene.',m:'Y = {{0}} + {{1}} + {{2}} + {{3}}',a:[['C'],['I'],['G'],['NX','X-M','X−M']],answer:'Y = C + I + G + NX',explain:'Utgiftsmetoden summerer privat konsum, investeringer, offentlige kjøp og nettoeksport.',derive:['Samlet etterspørsel etter norsk produksjon består av C, I, G og NX.','Derfor: Y = C + I + G + NX.']},
  {id:'nx',deck:'regnskap',topic:'Nasjonalregnskap',q:'Hva er nettoeksport?',hint:'Nettoeksport er eksport minus import.',m:'NX = {{0}} − {{1}}',a:[['X'],['M']],answer:'NX = X − M',explain:'Eksport trekker opp etterspørselen etter norsk produksjon. Import trekkes fra.',derive:['Netto betyr at vi trekker fra det som går motsatt vei.','Derfor: NX = X − M.']},
  {id:'sparing',deck:'regnskap',topic:'Sparing',q:'Hva er nasjonal sparing?',hint:'S er det som står igjen når C og G trekkes fra Y.',m:'S = {{0}} − {{1}} − {{2}}',a:[['Y'],['C'],['G']],answer:'S = Y − C − G',explain:'Nasjonal sparing er inntekten som ikke brukes til privat konsum eller offentlige kjøp.',derive:['Start med samlet inntekt Y.','Trekk fra privat konsum C og offentlige kjøp G.','Da står S = Y − C − G igjen.']},
  {id:'s-i-nx',deck:'regnskap',topic:'Sparing i åpen økonomi',q:'Hva er sammenhengen mellom sparing, investering og nettoeksport?',hint:'Bruk Y=C+I+G+NX og S=Y−C−G.',m:'S = {{0}} + {{1}}',a:[['I'],['NX','CA']],answer:'S = I + NX  ⇔  NX = S − I',explain:'I åpen økonomi kan sparing finansiere investering hjemme eller netto utlån til utlandet. Samme identitet kan også skrives NX = S − I.',derive:['Start: Y = C + I + G + NX.','Flytt C og G til venstre: Y − C − G = I + NX.','Siden S = Y − C − G får vi S = I + NX, som også gir NX = S − I.']},
  {id:'s-priv',deck:'regnskap',topic:'Privat sparing',q:'Hva er privat sparing?',hint:'Disponibel inntekt minus privat konsum.',m:'S<sub>priv</sub> = {{0}} − {{1}} − {{2}}',a:[['Y'],['T'],['C']],answer:'S_priv = Y − T − C',explain:'Privat sparing er husholdningenes inntekt etter skatt som ikke brukes til konsum. Y er inntekt/BNP, T er skatter, C er privat konsum.',derive:['Disponibel privat inntekt er Y − T.','Trekk fra konsum C.','Da får vi S_priv = Y − T − C.']},
  {id:'s-off',deck:'regnskap',topic:'Offentlig sparing',q:'Hva er offentlig sparing?',hint:'Skatteinntekter minus offentlige kjøp.',m:'S<sub>off</sub> = {{0}} − {{1}}',a:[['T'],['G']],answer:'S_off = T − G',explain:'Offentlig sparing er skatteinntekter minus offentlige kjøp. Hvis G > T, er offentlig sparing negativ.',derive:['Staten får inn T i skatter.','Staten bruker G på varer og tjenester.','Offentlig sparing blir S_off = T − G.']},
  {id:'s-total-components',deck:'regnskap',topic:'Samlet sparing',q:'Hvordan skrives samlet nasjonal sparing som privat pluss offentlig sparing?',hint:'Legg sammen privat og offentlig sparing.',m:'S = {{0}} + {{1}}',a:[['Spriv','S_priv','Sprivat'],['Soff','S_off','Soffentlig']],answer:'S = S_priv + S_off',explain:'Samlet nasjonal sparing er summen av privat sparing og offentlig sparing.',derive:['Privat sparing: S_priv = Y − T − C.','Offentlig sparing: S_off = T − G.','Summen blir S = Y − C − G.']},
  {id:'output-gap',deck:'regnskap',topic:'Produksjonsgap',q:'Hva er produksjonsgapet?',hint:'Faktisk minus potensiell produksjon, delt på potensiell produksjon.',m:'Ŷ<sub>t</sub> = ({{0}} − {{1}}) / {{2}}',a:[['Yt','Y_t'],['Ybar_t','Ȳt','Ypot','barYt','Y*'],['Ybar_t','Ȳt','Ypot','barYt','Y*']],answer:'Ŷ_t = (Y_t − Ȳ_t)/Ȳ_t. I prosent: ((Y_t − Ȳ_t)/Ȳ_t)·100.',explain:'Y_t er faktisk BNP/produksjon. Ȳ_t er potensiell eller trendmessig produksjon. Ŷ_t er produksjonsgapet.',derive:['Mål avviket: Y_t − Ȳ_t.','Del på Ȳ_t for å få et relativt avvik.','Gang med 100 hvis svaret skal stå i prosent.']},
  // === Vekst og Solow/Romer ===
  {id:'cd',deck:'vekst',topic:'Cobb–Douglas',q:'Hva er Cobb–Douglas-produksjonsfunksjonen?',hint:'Produksjon avhenger av teknologi, kapital og arbeid.',m:'Y = {{0}} <span class="dot">·</span> <span class="pow">{{1}}<sup>{{2}}</sup></span> <span class="dot">·</span> <span class="pow">{{3}}<sup>{{4}}</sup></span>',a:[['A'],['K'],['α','alpha'],['L'],['1−α','1-α','1-alpha','1−alpha']],answer:'Y = A · K^α · L^(1−α)',explain:'α er kapitalens produksjonselastisitet. 1−α er arbeidets elastisitet.',derive:['Kapital får vekt α.','Arbeid får resten av vekten: 1−α.','Teknologinivået A multipliserer hele uttrykket.']},
  {id:'per-worker',deck:'vekst',topic:'Per arbeider',q:'Hva er produksjon per arbeider når y=Y/L og k=K/L?',hint:'Del Cobb–Douglas på L.',m:'y = {{0}} <span class="dot">·</span> <span class="pow"><span class="static">k</span><sup>{{1}}</sup></span>',a:[['A'],['α','alpha']],answer:'y = A · k^α',explain:'Y/L = A K^α L^(1−α)/L = A(K/L)^α = A k^α.',derive:['Start med Y = A K^α L^(1−α).','Del på L.','Siden k = K/L får vi y = A k^α.']},
  {id:'solow-dk',deck:'vekst',topic:'Kapitalakkumulasjon',q:'Hva er Solow-ligningen for kapital per arbeider?',hint:'Investering per arbeider minus break-even-investering.',m:'Δk = {{0}} <span class="dot">·</span> {{1}} − ({{2}} + {{3}}) <span class="dot">·</span> {{4}}',a:[['s'],['f(k)','y'],['δ','delta'],['n'],['k']],answer:'Δk = s f(k) − (δ+n)k',explain:'Kapital per arbeider øker med sparing/investering og faller når kapital slites eller må fordeles på flere arbeidere.',derive:['Investering per arbeider er s f(k).','Break-even-investering er (δ+n)k.','Netto endring er investering minus break-even-investering.']},
  {id:'steady',deck:'vekst',topic:'Steady state',q:'Hva er steady-state-betingelsen i Solow?',hint:'I steady state er Δk = 0.',m:'{{0}} <span class="dot">·</span> {{1}} = ({{2}} + {{3}}) <span class="dot">·</span> <span class="blank star">{{4}}</span>',a:[['s'],['f(k*)','f(k^*)'],['δ','delta'],['n'],['k*','k^*']],answer:'s f(k*) = (δ+n)k*',explain:'Sett Δk=0. Da er investering akkurat lik break-even-investering.',derive:['Start med Δk = s f(k) − (δ+n)k.','I steady state er Δk = 0.','Dermed må s f(k*) = (δ+n)k*.']},
  {id:'growth-accounting',deck:'vekst',topic:'Vekstregnskap',q:'Hva er vekstregnskapet fra Cobb–Douglas?',hint:'Log-deriver produksjonsfunksjonen.',m:'gY = {{0}} + {{1}} + ({{2}})<span class="dot">·</span>{{3}}',a:[['gA'],['αgK','α*gK','alpha gK','alphagk'],['1−α','1-α','1-alpha','1−alpha'],['gL']],answer:'gY = gA + αgK + (1−α)gL',explain:'Produksjonsvekst dekomponeres i TFP-vekst og faktorvekster vektet med faktorandeler.',derive:['Ta log av Y = A K^α L^(1−α).','lnY = lnA + αlnK + (1−α)lnL.','Deriver over tid.']},
  {id:'mpk',deck:'vekst',topic:'Faktorpriser',q:'Hva er marginalproduktet av kapital i Cobb–Douglas?',hint:'Kapitalens faktorandel ganger produksjon per kapitalenhet.',m:'MPK = {{0}} · {{1}} / {{2}}',a:[['α','alpha'],['Y'],['K']],answer:'MPK = αY/K',explain:'MPK er marginalproduktet av kapital. α er kapitalens inntektsandel, Y er produksjon, K er kapital.',derive:['Deriver Y = AK^αL^(1−α) med hensyn på K.','Da får du MPK = αAK^(α−1)L^(1−α) = αY/K.']},
  {id:'mpl',deck:'vekst',topic:'Faktorpriser',q:'Hva er marginalproduktet av arbeid i Cobb–Douglas?',hint:'Arbeidets faktorandel ganger produksjon per arbeider.',m:'MPL = ({{0}} − {{1}}) · {{2}} / {{3}}',a:[['1'],['α','alpha'],['Y'],['L']],answer:'MPL = (1−α)Y/L',explain:'MPL er marginalproduktet av arbeid. 1−α er arbeidets inntektsandel, Y er produksjon, L er arbeidskraft.',derive:['Deriver Y = AK^αL^(1−α) med hensyn på L.','Da får du MPL = (1−α)AK^αL^(−α) = (1−α)Y/L.']},
  {id:'r-equals-mpk',deck:'vekst',topic:'Faktorpriser',q:'Hva er likevektsbetingelsen for kapitalleie ved perfekt konkurranse?',hint:'Bedriften leier kapital til marginalprodukt er lik kostnad.',m:'r = {{0}}',a:[['MPK']],answer:'r = MPK',explain:'r er leiepris/avkastningskrav på kapital. I profittmaksimum er r lik marginalproduktet av kapital.',derive:['Hvis MPK > r, lønner det seg å bruke mer kapital.','Hvis MPK < r, lønner det seg å bruke mindre kapital.','I optimum: r = MPK.']},
  {id:'w-equals-mpl',deck:'vekst',topic:'Faktorpriser',q:'Hva er likevektsbetingelsen for arbeidskraft ved perfekt konkurranse?',hint:'Bedriften ansetter til marginalprodukt er lik lønn.',m:'w = {{0}}',a:[['MPL']],answer:'w = MPL',explain:'w er lønn. I profittmaksimum er lønnen lik marginalproduktet av arbeid.',derive:['Hvis MPL > w, lønner det seg å ansette mer.','Hvis MPL < w, lønner det seg å ansette mindre.','I optimum: w = MPL.']},
  {id:'capital-share',deck:'vekst',topic:'Faktorandeler',q:'Hva er kapitalens inntektsandel i Cobb–Douglas?',hint:'Kapitalinntekt delt på total produksjon.',m:'rK / Y = {{0}}',a:[['α','alpha']],answer:'rK/Y = α',explain:'rK er samlet kapitalinntekt, Y er total produksjon, og α er kapitalens inntektsandel.',derive:['Bruk r = MPK = αY/K.','Multipliser med K: rK = αY.','Del på Y: rK/Y = α.']},
  {id:'labor-share',deck:'vekst',topic:'Faktorandeler',q:'Hva er arbeidets inntektsandel i Cobb–Douglas?',hint:'Lønnsinntekt delt på total produksjon.',m:'wL / Y = {{0}} − {{1}}',a:[['1'],['α','alpha']],answer:'wL/Y = 1−α',explain:'wL er samlet arbeidsinntekt, Y er total produksjon, og 1−α er arbeidets inntektsandel.',derive:['Bruk w = MPL = (1−α)Y/L.','Multipliser med L: wL = (1−α)Y.','Del på Y: wL/Y = 1−α.']},
  {id:'tfp-growth',deck:'vekst',topic:'TFP-residual',q:'Hvordan løser du vekstregnskapet for TFP-vekst?',hint:'Trekk kapital- og arbeidsbidrag fra BNP-veksten.',m:'gA = {{0}} − {{1}} − {{2}}',a:[['gY'],['αgK','alpha*gK','α*gK'],['(1-α)gL','(1−α)gL','1−αgL','(1-alpha)gL']],answer:'gA = gY − αgK − (1−α)gL',explain:'gA er TFP-vekst. Det er produksjonsveksten som ikke forklares av vekst i kapital og arbeid.',derive:['Start med gY = gA + αgK + (1−α)gL.','Flytt kapital- og arbeidsbidragene over på venstre side.']},
  {id:'relative-income',deck:'vekst',topic:'Inntektsforskjeller',q:'Hvordan sammenlignes produksjon per arbeider mellom to land i Cobb–Douglas?',hint:'TFP-forhold ganger kapitalforhold opphøyd i α.',m:'y<sub>i</sub>/y<sub>j</sub> = ({{0}}/{{1}}) · ({{2}}/{{3}})<sup>{{4}}</sup>',a:[['Ai','A_i'],['Aj','A_j'],['ki','k_i'],['kj','k_j'],['α','alpha']],answer:'y_i/y_j = (A_i/A_j)(k_i/k_j)^α',explain:'y_i/y_j er relativ inntekt per arbeider. A_i/A_j er relativ TFP. k_i/k_j er relativ kapital per arbeider.',derive:['Start med y = Ak^α for begge land.','Del uttrykket for land i på uttrykket for land j.']},
  {id:'solow-invest',deck:'vekst',topic:'Solow-investering',q:'Hva er investering per arbeider i Solow?',hint:'En fast andel av produksjon per arbeider spares og investeres.',m:'i<sub>t</sub> = {{0}} · {{1}}',a:[['s'],['yt','y_t']],answer:'i_t = s y_t',explain:'i_t er investering per arbeider, s er spareraten, y_t er produksjon per arbeider.',derive:['I Solow spares/investeres en andel s av produksjonen.','Per arbeider blir derfor i_t = s y_t.']},
  {id:'solow-dk-no-n',deck:'vekst',topic:'Kapitalakkumulasjon uten befolkningsvekst',q:'Hva er Solow-ligningen uten befolkningsvekst?',hint:'Investering minus kapitalslit.',m:'Δk = {{0}} · {{1}} − {{2}} · {{3}}',a:[['s'],['yt','y_t','f(k)'],['δ','d','delta'],['k']],answer:'Δk = sy − δk',explain:'Når n = 0, faller kapital per arbeider bare fordi kapital slites ned med rate δ.',derive:['Investering per arbeider er sy.','Kapitalslit per arbeider er δk.','Netto endring: Δk = sy − δk.']},
  {id:'steady-k',deck:'vekst',topic:'Solow steady state',q:'Hva er k* i Solow med Cobb–Douglas og befolkningsvekst?',hint:'Løs sAk^α = (δ+n)k for k.',m:'k* = ({{0}}·{{1}} / ({{2}} + {{3}}))<sup>1/(1−{{4}})</sup>',a:[['s'],['A'],['δ','d','delta'],['n'],['α','alpha']],answer:'k* = (sA/(δ+n))^(1/(1−α))',explain:'k* er steady-state kapital per arbeider. Høyere s og A øker k*, mens høyere δ og n reduserer k*.',derive:['Start med sAk^α = (δ+n)k.','Del på k^α og på δ+n.','Opphøy i 1/(1−α).']},
  {id:'steady-y',deck:'vekst',topic:'Solow steady-state produksjon',q:'Hva er produksjon per arbeider i steady state?',hint:'Sett k* inn i produksjonsfunksjonen.',m:'y* = {{0}} · ({{1}})<sup>{{2}}</sup>',a:[['A'],['k*','k^*'],['α','alpha']],answer:'y* = A(k*)^α',explain:'y* er steady-state produksjon per arbeider, A er teknologi, k* er steady-state kapital per arbeider.',derive:['Produksjonsfunksjonen er y = Ak^α.','I steady state setter vi k = k*.']},
  {id:'solow-consumption',deck:'vekst',topic:'Konsum i Solow',q:'Hva er konsum per arbeider når en andel s spares?',hint:'Den delen av produksjonen som ikke spares.',m:'c = ({{0}} − {{1}}) · {{2}}',a:[['1'],['s'],['y']],answer:'c = (1−s)y',explain:'c er konsum per arbeider, s er spareraten, y er produksjon per arbeider.',derive:['Produksjon per arbeider fordeles mellom konsum og investering.','Investering er sy.','Da er konsum c = y − sy = (1−s)y.']},
  {id:'solow-c-star',deck:'vekst',topic:'Konsum i steady state',q:'Hva er konsum per arbeider i steady state med befolkningsvekst?',hint:'Produksjon minus nødvendig investering.',m:'c* = {{0}}({{1}}) − ({{2}} + {{3}}){{4}}',a:[['f'],['k*','k^*'],['δ','d','delta'],['n'],['k*','k^*']],answer:'c* = f(k*) − (δ+n)k*',explain:'c* er konsum i steady state. f(k*) er produksjon, og (δ+n)k* er investering som må til for å holde k konstant.',derive:['I steady state må investering dekke kapitalslit og kapital til nye arbeidere.','Konsum er det som er igjen av produksjonen.']},
  {id:'golden-rule-no-n',deck:'vekst',topic:'Gylne regel uten befolkningsvekst',q:'Hva er den gylne regel uten befolkningsvekst?',hint:'Marginalproduktet av kapital lik kapitalslit.',m:'MPK = {{0}}',a:[['δ','d','delta']],answer:'MPK = δ',explain:'Uten befolkningsvekst maksimeres konsum når marginalproduktet av kapital er lik depresieringen δ.',derive:['Konsum i steady state er c = f(k) − δk.','Maksimer: f′(k) − δ = 0.','Dermed MPK = δ.']},
  {id:'golden-rule',deck:'vekst',topic:'Gylne regel med befolkningsvekst',q:'Hva er den gylne regel med befolkningsvekst?',hint:'Marginalproduktet av kapital lik break-even-raten.',m:'MPK = {{0}} + {{1}}',a:[['δ','d','delta'],['n']],answer:'MPK = δ + n',explain:'Med befolkningsvekst må kapitalens marginalprodukt dekke både kapitalslit δ og kapitaluttynning n.',derive:['Konsum i steady state er c = f(k) − (δ+n)k.','Maksimer: f′(k) − (δ+n) = 0.','Dermed MPK = δ+n.']},
  {id:'romer-y',deck:'vekst',topic:'Romer-produksjon',q:'Hva er produksjonsfunksjonen i den enkle Romer-modellen?',hint:'Ideer/teknologi opphøyd i γ ganger arbeidere i vareproduksjon.',m:'Y<sub>t</sub> = A<sub>t</sub><sup>{{0}}</sup> · {{1}}',a:[['γ','gamma'],['Lyt','L_y','L_y_t','Lᵧt']],answer:'Y_t = A_t^γ L_yt',explain:'Y_t er produksjon, A_t er kunnskaps-/teknologinivå, γ måler hvor viktige ideer er i produksjonen, L_yt er arbeidere i vareproduksjon.',derive:['Produksjon skapes av ideer A_t og arbeid i produksjon L_yt.','γ viser hvor sterkt ideer slår ut i produksjon.']},
  {id:'romer-delta-a',deck:'vekst',topic:'Romer idéproduksjon',q:'Hva er idéproduksjonen i den enkle Romer-modellen?',hint:'Forskningsproduktivitet ganger forskere.',m:'ΔA<sub>t+1</sub> = {{0}} · {{1}}',a:[['z'],['Lat','L_a','Lₐ','L_a_t']],answer:'ΔA_{t+1} = zL_at',explain:'ΔA_{t+1} er nye ideer, z er forskningsproduktivitet, L_at er arbeidskraft brukt i forskning.',derive:['Hver forsker produserer z nye ideer.','Med L_at forskere blir nye ideer zL_at.']},
  {id:'romer-ga',deck:'vekst',topic:'Romer teknologivekst',q:'Hvordan skrives vekstraten i kunnskap når ΔA = zL_a?',hint:'Del nye ideer på eksisterende kunnskapsnivå.',m:'g<sub>A</sub> = ΔA<sub>t+1</sub> / {{0}} = {{1}}{{2}} / {{3}}',a:[['At','A_t'],['z'],['Lat','L_a','Lₐ'],['At','A_t']],answer:'g_A = ΔA_{t+1}/A_t = zL_at/A_t',explain:'g_A er veksten i kunnskap/teknologi. Den er nye ideer relativt til eksisterende kunnskapsnivå.',derive:['Vekstrate = endring delt på nivå.','Bruk ΔA_{t+1} = zL_at.']},
  {id:'romer-labor',deck:'vekst',topic:'Romer ressursbegrensning',q:'Hva er arbeidskraftsbegrensningen i Romer-modellen?',hint:'Arbeidere i produksjon pluss forskere er total befolkning/arbeidskraft.',m:'{{0}} + {{1}} = {{2}}',a:[['Lyt','L_y','Lᵧt'],['Lat','L_a','Lₐ'],['Nt','N_t']],answer:'L_yt + L_at = N_t',explain:'L_yt er arbeid i vareproduksjon, L_at er arbeid i forskning, N_t er total arbeidskraft/befolkning.',derive:['Arbeidskraften må enten brukes i produksjon eller forskning.','Summen er total arbeidskraft N_t.']},
  {id:'romer-allocation',deck:'vekst',topic:'Romer forskerandel',q:'Hvordan skrives antall forskere hvis ℓ er forskerandelen?',hint:'Andel forskere ganger total befolkning.',m:'L<sub>at</sub> = {{0}} · {{1}}',a:[['ℓ','l','ell'],['Nt','N_t']],answer:'L_at = ℓN_t',explain:'ℓ er andelen av arbeidskraften som jobber med forskning, N_t er total arbeidskraft/befolkning.',derive:['Hvis andelen forskere er ℓ, og total arbeidskraft er N_t, er antall forskere ℓN_t.']},
  {id:'romer-bgp-ga',deck:'vekst',topic:'Romer balansert vekstbane',q:'Hva er teknologiveksten på balansert vekstbane i SAM3-Romer?',hint:'På BGP følger idéveksten befolkningsveksten.',m:'g<sub>A</sub>* = {{0}}',a:[['n']],answer:'g_A* = n',explain:'På balansert vekstbane vokser kunnskapsnivået med befolkningsveksten n i denne enkle Romer-versjonen.',derive:['Flere mennesker gir flere forskere over tid når forskerandelen er konstant.','På balansert vekstbane blir g_A* = n.']},
  {id:'romer-bgp-gy',deck:'vekst',topic:'Romer balansert vekstbane',q:'Hva er veksten i produksjon per arbeider på balansert vekstbane?',hint:'Produksjon per arbeider vokser med γ ganger idéveksten.',m:'g<sub>y</sub>* = {{0}} · {{1}}',a:[['γ','gamma'],['n']],answer:'g_y* = γn',explain:'g_y* er vekst i produksjon per arbeider, γ er idéenes betydning i produksjon, n er befolkningsvekst.',derive:['På BGP er g_A* = n.','Siden y avhenger av A^γ, blir g_y* = γg_A* = γn.']},
  // === Arbeidsmarked ===
  {id:'u-rate',deck:'arbeid',topic:'Ledighet',q:'Hva er ledighetsraten?',hint:'Arbeidsledige delt på arbeidsstyrken.',m:'u = <span class="frac"><span class="num">{{0}}</span><span class="den">{{1}}</span></span>',a:[['U'],['LF','L']],answer:'u = U / LF',explain:'U er arbeidsledige. LF er arbeidsstyrken.',derive:['Ledighetsraten er andelen av arbeidsstyrken som er arbeidsledig.','Dermed: u = U/LF.']},
  {id:'lf',deck:'arbeid',topic:'Arbeidsstyrke',q:'Hva består arbeidsstyrken av?',hint:'Sysselsatte pluss arbeidsledige.',m:'LF = {{0}} + {{1}}',a:[['E','N'],['U']],answer:'LF = E + U',explain:'Arbeidsstyrken er de som enten er i arbeid eller aktivt søker arbeid.',derive:['Arbeidsstyrken består av personer som tilbyr arbeid.','Det inkluderer sysselsatte E og arbeidsledige U.']},
  {id:'natural-u',deck:'arbeid',topic:'Naturlig ledighet',q:'Hva er naturlig ledighet i badekarmodellen?',hint:'Separasjoner delt på separasjoner pluss jobbfinning.',m:'u* = {{0}} / ({{1}} + {{2}})',a:[['s'],['s'],['f']],answer:'u* = s / (s+f)',explain:'I steady state er strømmen inn i ledighet lik strømmen ut av ledighet.',derive:['Strøm inn i ledighet: s(1−u).','Strøm ut av ledighet: fu.','Sett likt: s(1−u)=fu → u* = s/(s+f).']},
  {id:'okun',deck:'arbeid',topic:'Okuns lov',q:'Hva er Okuns lov?',hint:'Produksjonsgap og ledighetsgap beveger seg motsatt vei.',m:'<span class="blank tilde">{{0}}</span> = −{{1}}({{2}} − <span class="blank star">{{3}}</span>)',a:[['Y~','y~','Ytilde','Ŷ','Yhat','Ỹ'],['β','beta','2'],['u'],['u*','u^*']],answer:'Ŷ = −β(u−u*)  ⇔  u−u* = −β̃Ŷ. I SAM3 brukes ofte u−u* ≈ −0,5Ŷ.',explain:'Ŷ er produksjonsgapet, u er faktisk ledighet, u* er naturlig ledighet, og β/β̃ måler styrken i sammenhengen. Positivt produksjonsgap gir lavere ledighet enn normalt.',derive:['Når u > u*, er økonomien svak og produksjonsgapet negativt.','Derfor har sammenhengen minusfortegn.','Forelesningsvarianten u−u*≈−0,5Ŷ er samme idé med ledighetsgapet på venstre side.']},
  // === Inflasjon og pengepolitikk ===
  {id:'mvpy',deck:'inflasjon',topic:'Kvantitetsteori',q:'Hva er kvantitetsteorien?',hint:'Penger ganger omløpshastighet er lik nominelt BNP.',m:'{{0}}<span class="dot">·</span>{{1}} = {{2}}<span class="dot">·</span>{{3}}',a:[['M'],['V'],['P'],['Y']],answer:'M V = P Y',explain:'MV tilsvarer nominelt BNP, PY.',derive:['MV måler hvor mye penger som brukes i transaksjoner.','PY er nominelt BNP.']},
  {id:'mvpy-growth',deck:'inflasjon',topic:'Kvantitetsteori i vekstrater',q:'Hva blir kvantitetsteorien i vekstrater?',hint:'Ta vekstrater på begge sider av MV=PY.',m:'gM + gV = {{0}} + {{1}}',a:[['π','pi'],['gY']],answer:'gM + gV = π + gY',explain:'Siden vekst i P er inflasjon, får vi π = gM + gV − gY.',derive:['Start fra MV = PY.','Ta vekstrate: gM + gV = gP + gY.','Siden gP = π får du uttrykket.']},
  {id:'fisher',deck:'inflasjon',topic:'Fisher',q:'Hva er Fisher-ligningen?',hint:'Nominell rente er omtrent realrente pluss forventet inflasjon.',m:'i ≈ {{0}} + {{1}}',a:[['r'],['πe','π^e','πᵉ','pi^e']],answer:'i ≈ r + πᵉ',explain:'Fisher skiller nominell rente fra realrente.',derive:['Eksakt: 1+i = (1+r)(1+πᵉ).','For små rater brukes tilnærmingen i ≈ r + πᵉ.']},
  {id:'real-rate',deck:'inflasjon',topic:'Realrente',q:'Hvordan finner du realrenten omtrent?',hint:'Omorganiser Fisher-ligningen.',m:'r ≈ {{0}} − {{1}}',a:[['i'],['πe','π^e','πᵉ','pi^e']],answer:'r ≈ i − πᵉ',explain:'Realrenten er nominell rente justert for forventet inflasjon.',derive:['Start med Fisher: i ≈ r + πᵉ.','Trekk πᵉ fra begge sider.']},
  {id:'inflation-rate',deck:'inflasjon',topic:'Inflasjonsrate',q:'Hva er inflasjonsraten fra prisnivået?',hint:'Prisnivå relativt til forrige periode minus én.',m:'π<sub>t</sub> = {{0}} / {{1}} − {{2}}',a:[['Pt','P_t'],['Pt-1','P_t-1','P_{t-1}'],['1']],answer:'π_t = P_t / P_{t−1} − 1',explain:'π_t er inflasjon i periode t, P_t er prisnivået nå, og P_{t−1} er prisnivået i forrige periode.',derive:['Inflasjon måler prosentvis prisendring.','Del dagens prisnivå på forrige periodes prisnivå og trekk fra 1.']},
  {id:'quantity-inflation',deck:'inflasjon',topic:'Kvantitetsteori og inflasjon',q:'Hvis omløpshastigheten er stabil, hva sier kvantitetsteorien om inflasjon?',hint:'Sett gV = 0 i gM + gV = π + gY.',m:'π = {{0}} − {{1}}',a:[['gM'],['gY']],answer:'π = gM − gY',explain:'π er inflasjon, gM er vekst i pengemengde, gY er real BNP-vekst. Når gV = 0, gir pengevekst utover realvekst inflasjon.',derive:['Start med gM + gV = π + gY.','Sett gV = 0.','Løs for π.']},
  {id:'fisher-exact',deck:'inflasjon',topic:'Fisher eksakt',q:'Hva er den eksakte Fisher-ligningen?',hint:'Brutto nominell avkastning er brutto realavkastning ganger brutto forventet inflasjon.',m:'1 + i = (1 + {{0}})(1 + {{1}})',a:[['r'],['πe','π^e','πᵉ']],answer:'1+i = (1+r)(1+πᵉ)',explain:'i er nominell rente, r er realrente, πᵉ er forventet inflasjon.',derive:['En långiver krever real avkastning og kompensasjon for forventet prisvekst.','Bruttoeffektene multipliseres.']},
  {id:'fisher-sam3',deck:'inflasjon',topic:'Fisher SAM3-kortsiktvariant',q:'Hvilken Fisher-variant brukes ofte i SAM3-kortsiktsmodellen?',hint:'Realrente er nominell rente minus inflasjon.',m:'R<sub>t</sub> = {{0}} − {{1}}',a:[['it','i_t'],['πt','π_t','pi_t']],answer:'R_t = i_t − π_t',explain:'R_t er kortsiktig realrente, i_t er nominell rente, π_t er inflasjon. Dette er SAM3-kortsiktvarianten av Fisher-sammenhengen.',derive:['Start med realrente ≈ nominell rente − inflasjon.','Bruk periodens variabler: R_t = i_t − π_t.']},
  {id:'phillips-sam3',deck:'inflasjon',topic:'Phillipskurve med sjokk',q:'Hva er Phillipskurven med produksjonsgap og inflasjonssjokk?',hint:'Faktisk inflasjon er forventet inflasjon pluss press i økonomien pluss sjokk.',m:'π<sub>t</sub> = {{0}} + {{1}}·{{2}} + {{3}}',a:[['πe_t','π_t^e','πᵉt','pi_e'],['v','κ','kappa'],['Ŷt','Ŷ_t','Yhat_t','Ỹt'],['ot','o_t']],answer:'π_t = π_t^e + vŶ_t + o_t',explain:'π_t er faktisk inflasjon, π_t^e er forventet inflasjon, v måler hvor sterkt produksjonsgapet påvirker inflasjon, Ŷ_t er produksjonsgapet, o_t er kostnads-/tilbudssjokk.',derive:['Forventet inflasjon er utgangspunktet.','Positivt produksjonsgap gir høyere prispress.','Tilbudssjokk flytter inflasjonen direkte.']},
  // === Kortsiktig makro ===
  {id:'phillips',deck:'kortsikt',topic:'Phillipskurve',q:'Hva er Phillipskurven med forventninger og sjokk?',hint:'Faktisk inflasjon er forventet inflasjon pluss press i økonomien pluss kostnadssjokk.',m:'π<sub>t</sub> = {{0}} + {{1}}·{{2}} + {{3}}',a:[['πe_t','π_t^e','πᵉt','pi_e'],['v','κ','kappa'],['Ŷt','Ŷ_t','Yhat_t','Ỹt','Y~'],['ot','o_t']],answer:'π_t = π_t^e + vŶ_t + o_t',explain:'π_t er inflasjon, π_t^e forventet inflasjon, v/κ følsomhet for produksjonsgapet, Ŷ_t produksjonsgap, og o_t kostnads-/tilbudssjokk.',derive:['Forventet inflasjon er utgangspunktet.','Positivt produksjonsgap gir økt prispress.','Kostnads- og tilbudssjokk flytter inflasjonen direkte.']},
  {id:'mp-rule',deck:'kortsikt',topic:'MP-kurven',q:'Hva er den enkle MP-kurven/Taylor-regelen i SAM3?',hint:'Realrenten reagerer på inflasjonsgapet.',m:'R<sub>t</sub> = {{0}} + {{1}}(π<sub>t</sub> − {{2}})',a:[['rbar','r̄','r_bar'],['mbar','m','m_bar'],['pibar','πbar','π̄','pi_bar']],answer:'R_t = r̄ + m̄(π_t − π̄)',explain:'R_t er realrente, r̄ normal realrente, m̄ sentralbankens reaksjonsstyrke, π_t inflasjon og π̄ inflasjonsmålet.',derive:['Sentralbanken setter høyere realrente når inflasjonen er over målet.','Hvor kraftig renten økes bestemmes av m̄.']},
  {id:'is-curve',deck:'kortsikt',topic:'IS-kurven',q:'Hva er IS-kurven i SAM3-form?',hint:'Produksjonsgapet avhenger negativt av realrenten relativt til normal realrente.',m:'Ŷ<sub>t</sub> = {{0}} − {{1}}(R<sub>t</sub> − {{2}})',a:[['abar','ā','a_bar'],['bbar','b','b_bar'],['rbar','r̄','r_bar']],answer:'Ŷ_t = ā − b̄(R_t − r̄)',explain:'Ŷ_t er produksjonsgap. ā samler autonome etterspørselsforhold/sjokk. b̄ er rentefølsomhet. R_t er realrente. r̄ er normal/nøytral realrente.',derive:['Høyere realrente demper konsum, investering og etterspørsel.','Derfor faller produksjonsgapet når R_t stiger relativt til r̄.']},
  {id:'ad-curve',deck:'kortsikt',topic:'AD-kurven',q:'Hva blir AD-kurven når MP settes inn i IS?',hint:'Sett R_t − r̄ = m̄(π_t − π̄) inn i IS.',m:'Ŷ<sub>t</sub> = {{0}} − {{1}}{{2}}(π<sub>t</sub> − {{3}})',a:[['abar','ā','a_bar'],['bbar','b','b_bar'],['mbar','m','m_bar'],['pibar','πbar','π̄','pi_bar']],answer:'Ŷ_t = ā − b̄m̄(π_t − π̄)',explain:'AD viser negativ sammenheng mellom inflasjon og produksjonsgap fordi høyere inflasjon gir høyere rente og lavere etterspørsel.',derive:['IS: Ŷ_t = ā − b̄(R_t − r̄).','MP: R_t − r̄ = m̄(π_t − π̄).','Sett MP inn i IS.']},
  {id:'phillips-adaptive',deck:'kortsikt',topic:'Phillipskurve med adaptive forventninger',q:'Hva blir Phillipskurven når forventningene er adaptive?',hint:'Sett π_t^e = π_{t−1}.',m:'π<sub>t</sub> = {{0}} + {{1}}·{{2}} + {{3}}',a:[['πt-1','π_{t-1}','pi_t-1'],['v','κ','kappa'],['Ŷt','Ŷ_t','Yhat_t','Ỹt'],['ot','o_t']],answer:'π_t = π_{t−1} + vŶ_t + o_t',explain:'Adaptive forventninger betyr at forventet inflasjon settes lik forrige periodes inflasjon.',derive:['Start med π_t = π_t^e + vŶ_t + o_t.','Sett π_t^e = π_{t−1}.']},
  {id:'phillips-delta',deck:'kortsikt',topic:'Endring i inflasjon',q:'Hvordan kan Phillipskurven med adaptive forventninger skrives som endring i inflasjon?',hint:'Trekk π_{t−1} fra begge sider.',m:'Δπ<sub>t</sub> = {{0}}·{{1}} + {{2}}',a:[['v','κ','kappa'],['Ŷt','Ŷ_t','Yhat_t','Ỹt'],['ot','o_t']],answer:'Δπ_t = vŶ_t + o_t',explain:'Δπ_t er endringen i inflasjon. Positivt produksjonsgap eller positivt kostnadssjokk øker inflasjonen.',derive:['Start med π_t = π_{t−1} + vŶ_t + o_t.','Trekk π_{t−1} fra begge sider.']},
  {id:'phillips-unemployment',deck:'kortsikt',topic:'Phillipskurve med ledighet',q:'Hvordan skrives Phillipskurven med ledighetsgap?',hint:'Høyere ledighet enn naturlig ledighet trekker inflasjonen ned.',m:'π<sub>t</sub> = {{0}} − {{1}}({{2}} − {{3}}) + {{4}}',a:[['πe_t','π_t^e','πᵉt'],['β','beta'],['ut','u_t'],['u*','u^*'],['ot','o_t']],answer:'π_t = π_t^e − β(u_t−u*) + o_t',explain:'u_t er faktisk ledighet, u* er naturlig ledighet. Når u_t > u*, blir inflasjonspresset lavere.',derive:['Lav ledighet betyr høyt press og høyere inflasjon.','Derfor har ledighetsgapet negativt fortegn.']},
  {id:'multiplier',deck:'kortsikt',topic:'Keynesiansk multiplikator',q:'Hva er den enkle offentlige utgiftsmultiplikatoren uten skatt?',hint:'Endring i Y relativt til endring i G.',m:'ΔY = (1 / (1 − {{0}})) · Δ{{1}}',a:[['c'],['G']],answer:'ΔY = [1/(1−c)]ΔG',explain:'c er marginal konsumtilbøyelighet. G er offentlige kjøp. Multiplikatoren blir større jo høyere c er.',derive:['Start med Y = C + I + G.','La C = cY + annet.','En økning i G forsterkes gjennom konsum.']},
  {id:'multiplier-tax',deck:'kortsikt',topic:'Multiplikator med skatt',q:'Hva er multiplikatoren med proporsjonal skatt?',hint:'Skatt reduserer disponibel inntekt og dermed konsumresponsen.',m:'ΔY = (1 / (1 − {{0}}(1 − {{1}}))) · ΔG',a:[['c'],['t']],answer:'ΔY = [1/(1−c(1−t))]ΔG',explain:'c er marginal konsumtilbøyelighet, t er skattesats. Skatt gjør multiplikatoren mindre.',derive:['Disponibel inntekt er (1−t)Y.','Konsumresponsen blir c(1−t).','Multiplikatoren blir 1/[1−c(1−t)].']},
  {id:'multiplier-import',deck:'kortsikt',topic:'Multiplikator med importlekkasje',q:'Hva er multiplikatoren med skatt og importlekkasje?',hint:'Importlekkasje gjør multiplikatoren mindre.',m:'ΔY = (1 / (1 − {{0}}(1 − {{1}}) + {{2}})) · ΔG',a:[['c'],['t'],['m']],answer:'ΔY = [1/(1−c(1−t)+m)]ΔG',explain:'m er marginal importtilbøyelighet. Når mer av økt etterspørsel går til import, blir innenlandsk BNP-effekt mindre.',derive:['Skatt reduserer konsumresponsen.','Import trekker etterspørsel ut av innenlandsk økonomi.','Derfor kommer +m i nevneren.']},
  {id:'asad-steady-y',deck:'kortsikt',topic:'Steady state i AS-AD',q:'Hva er produksjonsgapet i steady state i AS-AD?',hint:'Økonomien er på potensielt nivå.',m:'Ŷ = {{0}}',a:[['0']],answer:'Ŷ = 0',explain:'I steady state er faktisk produksjon lik potensiell produksjon, så produksjonsgapet er null.',derive:['Steady state betyr ingen press eller ledig kapasitet.','Derfor er produksjonsgapet lukket.']},
  {id:'asad-steady-pi',deck:'kortsikt',topic:'Steady state i AS-AD',q:'Hva er inflasjonen i steady state i AS-AD?',hint:'Inflasjonen er lik inflasjonsmålet.',m:'π = {{0}}',a:[['π*','πbar','π̄','pibar']],answer:'π = π*',explain:'I steady state er inflasjonen på målet. I SAM3 kan målet skrives π̄ eller π*.',derive:['Når sjokk er borte og økonomien er stabil, får sentralbanken inflasjonen tilbake til målet.']},
  {id:'asad-steady-r',deck:'kortsikt',topic:'Steady state i AS-AD',q:'Hva er realrenten i steady state i AS-AD?',hint:'Realrenten er normal/nøytral realrente.',m:'R = {{0}}',a:[['rbar','r̄','r*','r^*']],answer:'R = r̄',explain:'I steady state er realrenten lik normal/nøytral realrente.',derive:['Når inflasjonen er på målet, er inflasjonsgapet null.','MP-regelen gir da R = r̄.']},
  // === Åpen økonomi ===
  {id:'realkurs',deck:'apen',topic:'Realvalutakurs',q:'Hva er realvalutakursen når S er kroner per utenlandsk valuta?',hint:'Nominell kurs ganger utenlandsk prisnivå delt på norsk prisnivå.',m:'Q = {{0}} · {{1}} / {{2}}',a:[['S','e'],['P*','P^*'],['P']],answer:'Q = SP*/P',explain:'Q er realvalutakurs. S er nominell valutakurs i kroner per utenlandsk valuta. P* er utenlandsk prisnivå. P er norsk prisnivå.',derive:['Gjør utenlandske priser om til kroner: SP*.','Sammenlign med norske priser ved å dele på P.','Med norsk konvensjon betyr S opp svakere krone.']},
  {id:'uip',deck:'apen',topic:'UIP',q:'Hva er udekket renteparitet med risikopremie?',hint:'Innenlandsk rente lik utenlandsk rente pluss forventet depresiering pluss risikopremie.',m:'i = {{0}} + ({{1}} − {{2}})/{{3}} + {{4}}',a:[['i*','i^*'],['S_e','S^e_{t+1}','Se'],['S_t','St','S'],['S_t','St','S'],['ρ','rho']],answer:'i = i* + (S^e_{t+1} − S_t)/S_t + ρ',explain:'i er innenlandsk rente, i* utenlandsk rente, S_t dagens valutakurs, S^e_{t+1} forventet fremtidig valutakurs, og ρ risikopremie.',derive:['Investorer sammenligner forventet avkastning hjemme og ute.','Forventet kronesvekkelse er (S^e_{t+1}−S_t)/S_t.','Risikopremien ρ legges til hvis norske aktiva krever ekstra kompensasjon.']},
  {id:'ppp',deck:'apen',topic:'Kjøpekraftsparitet',q:'Hva er enkel kjøpekraftsparitet når S er kroner per utenlandsk valuta?',hint:'Valutakursen gjør prisnivåene like målt i samme valuta.',m:'S = {{0}} / {{1}}',a:[['P'],['P*','P^*']],answer:'S = P/P*',explain:'S er nominell valutakurs, P er innenlandsk prisnivå, P* er utenlandsk prisnivå. PPP er en langsiktig referanse.',derive:['Law of one price: P = SP*.','Løs for S: S = P/P*.']},
  {id:'law-one-price',deck:'apen',topic:'Law of one price',q:'Hva sier law of one price?',hint:'Samme vare skal koste det samme målt i samme valuta.',m:'P = {{0}} · {{1}}',a:[['S'],['P*','P^*']],answer:'P = SP*',explain:'P er innenlandsk pris, S er kroner per utenlandsk valuta, P* er utenlandsk pris. Gjelder best for like, handlede varer uten friksjoner.',derive:['Utenlandske priser må omregnes til kroner med S.','Da skal samme vare ha pris P = SP*.']},
  {id:'trilemma',deck:'apen',topic:'Trilemmaet',q:'Hva er de tre målene i trilemmaet?',hint:'Et land kan normalt bare ha to av tre.',m:'{{0}} + {{1}} + {{2}}',a:[['fast valutakurs','fastkurs'],['fri kapitalflyt','frie kapitalbevegelser','kapitalflyt'],['selvstendig pengepolitikk','egen pengepolitikk']],answer:'Fast valutakurs + fri kapitalflyt + selvstendig pengepolitikk',explain:'Trilemmaet sier at et land normalt bare kan velge to av disse tre samtidig.',derive:['Fast kurs krever at renten forsvarer valutakursen.','Fri kapitalflyt gjør renteavvik vanskelige å opprettholde.','Derfor begrenses selvstendig pengepolitikk.']},
  // === Finanspolitikk ===
  {id:'debt-dynamics',deck:'finans',topic:'Statsbudsjett og gjeldsdynamikk',q:'Hva er statens gjeldsdynamikk i nivå?',hint:'Gammel gjeld med renter pluss primærunderskudd.',m:'B<sub>t+1</sub> = (1 + {{0}})B<sub>t</sub> + {{1}} − {{2}}',a:[['r'],['G_t','Gt','G'],['T_t','Tt','T']],answer:'B_{t+1} = (1+r)B_t + G_t − T_t',explain:'B_t er offentlig gjeld, r er realrente, G_t er offentlige utgifter/kjøp, T_t er skatteinntekter. G_t−T_t er primærunderskudd.',derive:['Staten starter med gjeld B_t.','Renter gjør den til (1+r)B_t.','Legg til primærunderskuddet G_t−T_t.']},
  {id:'debt-primary',deck:'finans',topic:'Primærunderskudd',q:'Hvordan kan gjeldsdynamikken skrives med primærunderskudd?',hint:'Ny gjeld er gammel gjeld med renter pluss primærunderskudd.',m:'B<sub>t+1</sub> = (1 + {{0}})B<sub>t</sub> + {{1}}',a:[['r'],['primærunderskudd','primary deficit','D_t','Dt']],answer:'B_{t+1} = (1+r)B_t + primærunderskudd',explain:'Primærunderskudd er offentlige utgifter utenom renter minus skatteinntekter.',derive:['Samle G_t−T_t i ett begrep.','Da får du B_{t+1} = (1+r)B_t + primærunderskudd.']},
  {id:'debt-ratio',deck:'finans',topic:'Gjeldsgrad',q:'Hva er standard formel for gjeld som andel av BNP?',hint:'Gammel gjeldsgrad justert for rente og vekst pluss primærunderskudd som andel av BNP.',m:'b<sub>t+1</sub> = ((1 + {{0}})/(1 + {{1}}))b<sub>t</sub> + {{2}}',a:[['r'],['g'],['d_t','dt','d']],answer:'b_{t+1} = [(1+r)/(1+g)]b_t + d_t',explain:'b_t er gjeld/BNP, r er realrente, g er BNP-vekst, d_t er primærunderskudd som andel av BNP. Presis timing av d_t kan variere.',derive:['Del gjeldsdynamikken på BNP.','Gammel gjeld vokser med rente, mens BNP-vekst gjør gjeldsgraden lavere.']},
  {id:'debt-rg',deck:'finans',topic:'Gjeldsbærekraft',q:'Hva er nøkkelbetingelsen som gjør gjeldsgrad lettere å stabilisere?',hint:'BNP-vekst høyere enn realrenten.',m:'{{0}} > {{1}}',a:[['g'],['r']],answer:'g > r',explain:'Når BNP vokser raskere enn realrenten, blir gammel gjeld mindre tung relativt til BNP. Hvis r > g, vokser gjeldsgraden lettere.',derive:['Gjeldsbrøken inneholder (1+r)/(1+g).','Hvis g > r, er denne faktoren under 1.']},
  {id:'handlingsregel',deck:'finans',topic:'Handlingsregelen',q:'Hva er enkel formel for handlingsregelen?',hint:'Bruk av oljepenger over tid omtrent lik 3 prosent av fondet.',m:'Oljepengebruk ≈ {{0}} · {{1}}',a:[['0.03','3%','0,03'],['SPU','fondet','oljefondet']],answer:'Oljepengebruk ≈ 0,03 · SPU',explain:'SPU er Statens pensjonsfond utland. 0,03 er forventet realavkastning på 3 prosent.',derive:['Hvis fondet realavkaster omtrent 3 prosent, kan staten over tid bruke 3 prosent uten å tære på realverdien.']}
];
