// SAM3 Formelquiz — SVG-figurer
// Hver figur er en funksjon som returnerer en SVG-streng (1000×620-viewBox).
// Registreres i figures{}-objektet, som leses av formelquiz-app.js for «Vis figur»-knappen.

const N='#0f172a',G='#15803d',R='#dc2626',B='#2563eb',O='#ea580c';
function defs(id){return `<defs><marker id="a${id}" markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto"><path d="M0 0 L9 4.5 L0 9 Z" fill="${N}"/></marker><marker id="g${id}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="${G}"/></marker><marker id="r${id}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="${R}"/></marker><marker id="b${id}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="${B}"/></marker></defs>`}
const svg=s=>`<svg viewBox="0 0 1000 620">${s}</svg>`;
const head=(t,f)=>`<text x="500" y="50" text-anchor="middle" class="title navy">${t}</text><text x="500" y="98" text-anchor="middle" class="formula navy">${f}</text>`;
const note=(y,t)=>`<rect x="70" y="${y}" width="860" height="42" rx="12" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1.5"/><text x="500" y="${y+27}" text-anchor="middle" class="small navy">${t}</text>`;
function box(x,bg,st,top,sym,bot,w=132,h=132,y=220){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="14" fill="${bg}" stroke="${st}" stroke-width="2"/><text x="${x+w/2}" y="${y+46}" text-anchor="middle" class="small" fill="${st}">${top}</text><text x="${x+w/2}" y="${y+86}" text-anchor="middle" class="title" fill="${st}">${sym}</text><text x="${x+w/2}" y="${y+114}" text-anchor="middle" class="small navy">${bot}</text>`}
function fBnp(){return svg(`${defs('bnp')}${head('BNP etter utgiftsmetoden','Y = C + I + G + NX')}<rect x="58" y="220" width="118" height="132" rx="18" fill="#f8fafc" stroke="${N}" stroke-width="2"/><text x="117" y="292" text-anchor="middle" class="title navy">Y</text><text x="117" y="326" text-anchor="middle" class="small navy">BNP</text><text x="204" y="298" text-anchor="middle" class="label navy">=</text><rect x="234" y="190" width="736" height="200" rx="26" fill="none" stroke="#cbd5e1" stroke-width="2"/><text x="602" y="207" text-anchor="middle" class="small navy">komponentene som til sammen utgjør Y</text>${box(255,'#fef2f2',R,'Konsum','C','husholdn.')}<text x="410" y="298" text-anchor="middle" class="label navy">+</text>${box(430,'#eff6ff',B,'Investering','I','bedrifter')}<text x="585" y="298" text-anchor="middle" class="label navy">+</text>${box(605,'#f0fdf4',G,'Offentlig','G','stat/komm.')}<text x="760" y="298" text-anchor="middle" class="label navy">+</text>${box(780,'#fff7ed',O,'Nettoeksport','NX','X − M')}${note(470,'BNP fra utgiftssiden er summen av etterspørselen etter norsk produksjon.')}`)}
function fNx(){return svg(`${defs('nx')}${head('Nettoeksport','NX = X − M')}<rect x="95" y="215" width="250" height="170" rx="22" fill="#eff6ff" stroke="${B}" stroke-width="2"/><text x="220" y="307" text-anchor="middle" class="title blue">Norge</text><rect x="655" y="215" width="250" height="170" rx="22" fill="#f0fdf4" stroke="${G}" stroke-width="2"/><text x="780" y="307" text-anchor="middle" class="title green">Utlandet</text><line x1="355" y1="265" x2="640" y2="265" stroke="${G}" stroke-width="3.5" marker-end="url(#gnx)"/><line x1="645" y1="335" x2="360" y2="335" stroke="${R}" stroke-width="3.5" marker-end="url(#rnx)"/><text x="500" y="245" text-anchor="middle" class="label green">Eksport (X)</text><text x="500" y="380" text-anchor="middle" class="label red">Import (M)</text>${note(480,'Nettoeksport er eksport minus import. NX > 0 når eksporten er størst.')}`)}
function fSparing(){return svg(`${head('Nasjonal sparing','S = Y − C − G')}${box(85,'#f8fafc',N,'Inntekt','Y','total',165,150,215)}<text x="285" y="304" text-anchor="middle" class="label navy">−</text>${box(315,'#fef2f2',R,'Konsum','C','privat',165,150,215)}<text x="515" y="304" text-anchor="middle" class="label navy">−</text>${box(545,'#eff6ff',B,'Offentlig','G','kjøp',165,150,215)}<text x="745" y="304" text-anchor="middle" class="label navy">=</text>${box(775,'#f0fdf4',G,'Rest','S','sparing',165,150,215)}<text x="500" y="405" text-anchor="middle" class="small navy">S er det som står igjen når C og G trekkes fra Y.</text>${note(480,'Nasjonal sparing er inntekt som ikke brukes til privat konsum eller offentlige kjøp.')}`)}
function fSIX(){return svg(`${head('Sparing, investering og nettoeksport','S = I + NX')}<rect x="100" y="245" width="180" height="130" rx="20" fill="#f0fdf4" stroke="${G}" stroke-width="2"/><text x="190" y="298" text-anchor="middle" class="label green">Sparing</text><text x="190" y="335" text-anchor="middle" class="title green">S</text><text x="330" y="322" text-anchor="middle" class="label navy">=</text><rect x="390" y="178" width="470" height="285" rx="26" fill="none" stroke="#cbd5e1" stroke-width="2"/><text x="625" y="205" text-anchor="middle" class="small navy">to mulige plasseringer av sparing</text><rect x="455" y="230" width="330" height="85" rx="18" fill="#eff6ff" stroke="${B}" stroke-width="2"/><text x="620" y="283" text-anchor="middle" class="label blue">Investeringer (I)</text><text x="620" y="348" text-anchor="middle" class="label navy">+</text><rect x="455" y="375" width="330" height="85" rx="18" fill="#fff7ed" stroke="${O}" stroke-width="2"/><text x="620" y="428" text-anchor="middle" class="label orange">Nettoeksport (NX)</text>${note(500,'I åpen økonomi kan sparing finansiere investeringer hjemme eller netto utlån til utlandet.')}`)}
function fCD(){return svg(`${defs('cd')}<text x="500" y="50" text-anchor="middle" class="title navy">Cobb–Douglas</text><text x="500" y="98" text-anchor="middle" class="formula navy">Y = A K<tspan baseline-shift="super" font-size="23">α</tspan> L<tspan baseline-shift="super" font-size="23">(1−α)</tspan></text><rect x="95" y="165" width="250" height="75" rx="16" fill="#f0fdf4" stroke="${G}" stroke-width="2"/><text x="220" y="212" text-anchor="middle" class="label green">Teknologi (A)</text><rect x="95" y="270" width="250" height="75" rx="16" fill="#fef2f2" stroke="${R}" stroke-width="2"/><text x="220" y="318" text-anchor="middle" class="label red">Kapital (Kᵅ)</text><rect x="95" y="375" width="250" height="75" rx="16" fill="#eff6ff" stroke="${B}" stroke-width="2"/><text x="220" y="423" text-anchor="middle" class="label blue">Arbeid (L¹⁻ᵅ)</text><rect x="455" y="250" width="195" height="125" rx="22" fill="#f8fafc" stroke="${N}" stroke-width="2"/><text x="552" y="302" text-anchor="middle" class="label navy">Produksjons-</text><text x="552" y="332" text-anchor="middle" class="label navy">maskin</text><line x1="350" y1="203" x2="452" y2="278" stroke="${G}" stroke-width="3" marker-end="url(#gcd)"/><line x1="350" y1="308" x2="452" y2="310" stroke="${R}" stroke-width="3" marker-end="url(#rcd)"/><line x1="350" y1="413" x2="452" y2="342" stroke="${B}" stroke-width="3" marker-end="url(#bcd)"/><line x1="652" y1="313" x2="790" y2="313" stroke="${N}" stroke-width="3.5" marker-end="url(#acd)"/><rect x="805" y="258" width="115" height="110" rx="18" fill="#fff7ed" stroke="${O}" stroke-width="2"/><text x="862" y="325" text-anchor="middle" class="title orange">Y</text><rect x="260" y="495" width="480" height="62" rx="16" fill="#fff" stroke="${B}" stroke-width="2"/><text x="500" y="521" text-anchor="middle" class="small navy">α = kapitalens vekt</text><text x="500" y="546" text-anchor="middle" class="small navy">1−α = arbeidets vekt</text>`)}
function fPerWorker(){return svg(`${defs('pw')}<text x="500" y="50" text-anchor="middle" class="title navy">Produksjon per arbeider</text><text x="500" y="98" text-anchor="middle" class="formula navy">y = A k<tspan baseline-shift="super" font-size="23">α</tspan></text><line x1="160" y1="470" x2="850" y2="470" class="axis" marker-end="url(#apw)"/><line x1="160" y1="470" x2="160" y2="150" class="axis" marker-end="url(#apw)"/><path d="M160 470 C250 315 405 230 570 205 C680 190 765 185 825 185" fill="none" stroke="${B}" stroke-width="4.5"/><text x="640" y="175" class="label blue serif">y = A k<tspan baseline-shift="super" font-size="12">α</tspan></text><text x="500" y="545" text-anchor="middle" class="label navy">Kapital per arbeider (k)</text><text x="95" y="245" text-anchor="middle" class="label navy" transform="rotate(-90 95 245)">Produksjon per arbeider (y)</text><rect x="610" y="315" width="270" height="82" rx="16" fill="#fff" stroke="${B}" stroke-width="2"/><text x="745" y="348" text-anchor="middle" class="small navy">Kurven flater ut:</text><text x="745" y="377" text-anchor="middle" class="small blue">avtakende grenseprodukt</text>${note(555,'Mer kapital per arbeider øker produksjonen, men effekten avtar.')}`)}
function greenY(x){const u=(x-130)/750;return 470-330*(1-Math.exp(-3.2*u))/(1-Math.exp(-3.2));}
function redY(x){return 470-.37*(x-130);}
function greenPath(){let p=[];for(let x=130;x<=880;x+=10)p.push(x.toFixed(1)+','+greenY(x).toFixed(1));return p.join(' ');}
function curveKey(x,y){return `<rect x="${x}" y="${y}" width="220" height="94" rx="12" fill="#fff" stroke="#e2e8f0" stroke-width="1.5"/><text x="${x+110}" y="${y+24}" text-anchor="middle" class="small muted">Kurver</text><line x1="${x+22}" y1="${y+48}" x2="${x+70}" y2="${y+48}" stroke="${G}" stroke-width="4"/><text x="${x+88}" y="${y+54}" class="label green serif">s f(k)</text><line x1="${x+22}" y1="${y+76}" x2="${x+70}" y2="${y+76}" stroke="${R}" stroke-width="3"/><text x="${x+88}" y="${y+82}" class="label red serif">(δ+n)k</text>`;}
function fSolow(kind){const x=340,yg=greenY(x),yr=redY(x),xs=656,ys=greenY(xs);const title=kind==='steady'?'Solow: steady state':'Solow: kapitalakkumulasjon';const form=kind==='steady'?'s f(k*) = (δ+n)k*':'Δk = s f(k) − (δ+n)k';const extra=kind==='steady'?`<circle cx="${xs}" cy="${ys}" r="9" fill="${N}"/><line x1="${xs}" y1="470" x2="${xs}" y2="${ys}" class="guide"/><text x="${xs-18}" y="522" class="label navy">k*</text><text x="305" y="522" class="small green">Δk &gt; 0</text><text x="720" y="522" class="small red">Δk &lt; 0</text>`:`<text x="735" y="438" text-anchor="middle" class="small navy">Når grønn kurve ligger over rød linje, øker k.</text>`;return svg(`${defs(kind)}${head(title,form)}<line x1="130" y1="470" x2="870" y2="470" class="axis" marker-end="url(#a${kind})"/><line x1="130" y1="470" x2="130" y2="135" class="axis" marker-end="url(#a${kind})"/><polyline points="${greenPath()}" fill="none" stroke="${G}" stroke-width="4.5" stroke-linecap="round" stroke-linejoin="round"/><line x1="130" y1="470" x2="880" y2="${redY(880)}" stroke="${R}" stroke-width="3.5"/><text x="515" y="545" text-anchor="middle" class="label navy">Kapital per arbeider (k)</text><text x="72" y="270" text-anchor="middle" class="label navy" transform="rotate(-90 72 270)">Investering / break-even</text><line x1="${x}" y1="470" x2="${x}" y2="${yg}" class="guide"/><line x1="${x}" y1="${yg}" x2="${x}" y2="${yr}" stroke="${B}" stroke-width="3"/><circle cx="${x}" cy="${yg}" r="8" fill="${G}"/><circle cx="${x}" cy="${yr}" r="8" fill="${R}"/><text x="${x+24}" y="${(yg+yr)/2+5}" class="label blue">Δk</text>${curveKey(685,280)}${extra}${note(555,kind==='steady'?'I steady state er investering akkurat lik det som trengs for å holde k konstant.':'Kapital per arbeider øker når investeringene er større enn break-even-investeringen.')}`)}
function fNaturalU(){return svg(`${defs('nu')}<text x="500" y="50" text-anchor="middle" class="title navy">Naturlig ledighet</text><text x="405" y="105" text-anchor="middle" class="formula navy">u*</text><text x="455" y="105" text-anchor="middle" class="formula navy">=</text><text x="535" y="86" text-anchor="middle" class="formula red">s</text><line x1="500" y1="102" x2="570" y2="102" stroke="${N}" stroke-width="3"/><text x="535" y="138" text-anchor="middle" class="formula navy"><tspan class="red">s</tspan><tspan>+</tspan><tspan class="green">f</tspan></text><rect x="100" y="185" width="230" height="90" rx="18" fill="#fff" stroke="${R}" stroke-width="2"/><text x="215" y="222" text-anchor="middle" class="label red">Separasjoner (s)</text><text x="215" y="252" text-anchor="middle" class="small navy">inn i ledighet</text><rect x="670" y="185" width="230" height="90" rx="18" fill="#fff" stroke="${G}" stroke-width="2"/><text x="785" y="222" text-anchor="middle" class="label green">Jobbfinning (f)</text><text x="785" y="252" text-anchor="middle" class="small navy">ut av ledighet</text><path d="M360 325 C400 295 600 295 640 325 L612 440 C570 466 430 466 388 440 Z" fill="#eff6ff" stroke="${N}" stroke-width="2"/><path d="M400 380 C460 364 540 364 600 380 L585 426 C535 442 465 442 415 426 Z" fill="#bfdbfe"/><text x="500" y="414" text-anchor="middle" class="title navy">Ledighet (u*)</text><path d="M300 275 C350 305 365 318 386 342" fill="none" stroke="${R}" stroke-width="3.5" marker-end="url(#rnu)"/><path d="M616 384 C660 370 685 338 718 280" fill="none" stroke="${G}" stroke-width="3.5" marker-end="url(#gnu)"/><rect x="660" y="425" width="250" height="80" rx="16" fill="#fff" stroke="${B}" stroke-width="2"/><text x="785" y="457" text-anchor="middle" class="small navy">s opp → u* opp</text><text x="785" y="485" text-anchor="middle" class="small navy">f opp → u* ned</text>${note(545,'Naturlig ledighet bestemmes av strømmen inn i og ut av ledighet.')}`)}
function fPhillips(){return svg(`${defs('ph')}<text x="500" y="50" text-anchor="middle" class="title navy">Forventningsutvidet Phillipskurve</text><text x="500" y="98" text-anchor="middle" class="formula navy">π = πᵉ + κỸ</text><line x1="150" y1="470" x2="850" y2="470" class="axis" marker-end="url(#aph)"/><line x1="150" y1="470" x2="150" y2="145" class="axis" marker-end="url(#aph)"/><path d="M260 395 L800 195" stroke="${B}" stroke-width="4.5"/><rect x="600" y="145" width="250" height="52" rx="14" fill="#fff" stroke="${B}" stroke-width="2"/><text x="725" y="179" text-anchor="middle" class="label blue">π = πᵉ + κỸ</text><line x1="150" y1="395" x2="260" y2="395" stroke="${R}" stroke-width="2" stroke-dasharray="7 6"/><line x1="260" y1="470" x2="260" y2="395" stroke="${R}" stroke-width="2" stroke-dasharray="7 6"/><circle cx="260" cy="395" r="8" fill="${R}"/><text x="105" y="400" class="label red">πᵉ</text><text x="760" y="520" text-anchor="middle" class="label navy">Produksjonsgap (Ỹ)</text><text x="110" y="150" text-anchor="end" class="label navy">Inflasjon (π)</text><circle cx="650" cy="252" r="9" fill="${B}"/><line x1="650" y1="470" x2="650" y2="252" stroke="${B}" stroke-width="2" stroke-dasharray="7 6"/><line x1="150" y1="252" x2="650" y2="252" stroke="${B}" stroke-width="2" stroke-dasharray="7 6"/><text x="650" y="500" text-anchor="middle" class="small blue">positivt gap</text><rect x="575" y="330" width="300" height="80" rx="16" fill="#fff" stroke="${G}" stroke-width="2"/><text x="725" y="363" text-anchor="middle" class="small navy">κ viser hvor sterkt π</text><text x="725" y="390" text-anchor="middle" class="small navy">reagerer på produksjonsgapet.</text>${note(545,'Faktisk inflasjon er forventet inflasjon pluss effekten av press i økonomien.')}`)}
function fIsMp(){return svg(`${defs('ismp')}${head('IS–MP-likevekt','Ỹ = −α(r − r*)')}<line x1="150" y1="470" x2="850" y2="470" class="axis" marker-end="url(#aismp)"/><line x1="150" y1="470" x2="150" y2="150" class="axis" marker-end="url(#aismp)"/><text x="500" y="545" text-anchor="middle" class="label navy">Produksjonsgap (Ỹ)</text><text x="100" y="160" text-anchor="middle" class="label navy" transform="rotate(-90 100 300)">Realrente (r)</text><line x1="200" y1="200" x2="800" y2="430" stroke="${B}" stroke-width="4.5"/><text x="700" y="225" class="label blue serif">IS</text><line x1="150" y1="320" x2="850" y2="320" stroke="${R}" stroke-width="3.5" stroke-dasharray="0"/><text x="780" y="305" class="label red">MP: r*</text><circle cx="500" cy="320" r="9" fill="${N}"/><line x1="500" y1="470" x2="500" y2="320" stroke="#94a3b8" stroke-width="2" stroke-dasharray="6 6"/><text x="500" y="495" text-anchor="middle" class="label navy">Ỹ = 0</text><line x1="200" y1="380" x2="800" y2="380" stroke="${R}" stroke-width="3" stroke-dasharray="6 4"/><text x="170" y="376" class="small red">MP'</text><text x="710" y="375" class="small red">lavere r</text>${note(555,'Sentralbankens MP-regel setter realrenten; IS-kurven gir produksjonsgapet ved den renten.')}`)}
function fAsAd(){return svg(`${defs('asad')}${head('AS–AD-likevekt','Ỹ = −γ(π − π*)')}<line x1="150" y1="470" x2="850" y2="470" class="axis" marker-end="url(#aasad)"/><line x1="150" y1="470" x2="150" y2="150" class="axis" marker-end="url(#aasad)"/><text x="500" y="545" text-anchor="middle" class="label navy">Produksjonsgap (Ỹ)</text><text x="100" y="160" text-anchor="middle" class="label navy" transform="rotate(-90 100 300)">Inflasjon (π)</text><line x1="200" y1="180" x2="800" y2="450" stroke="${B}" stroke-width="4.5"/><text x="720" y="195" class="label blue serif">AD</text><line x1="200" y1="430" x2="800" y2="200" stroke="${G}" stroke-width="4.5"/><text x="720" y="225" class="label green serif">AS</text><circle cx="500" cy="315" r="9" fill="${N}"/><line x1="500" y1="470" x2="500" y2="315" stroke="#94a3b8" stroke-width="2" stroke-dasharray="6 6"/><line x1="150" y1="315" x2="500" y2="315" stroke="#94a3b8" stroke-width="2" stroke-dasharray="6 6"/><text x="125" y="320" text-anchor="end" class="label navy">π*</text><text x="500" y="495" text-anchor="middle" class="label navy">Ỹ = 0</text><line x1="240" y1="200" x2="840" y2="465" stroke="${B}" stroke-width="3" stroke-dasharray="6 4"/><text x="190" y="195" class="small blue">AD'</text>${note(555,'Likevekten er der AS og AD møtes — kortsiktige sjokk skifter AD eller AS.')}`)}
function fRomer(){return svg(`${defs('romer')}${head('Romer-modellen','gA = θ · Lₐ')}<rect x="100" y="200" width="240" height="170" rx="20" fill="#eff6ff" stroke="${B}" stroke-width="2"/><text x="220" y="245" text-anchor="middle" class="label blue">Forskere</text><text x="220" y="295" text-anchor="middle" class="title blue">Lₐ</text><text x="220" y="335" text-anchor="middle" class="small navy">arbeid i FoU</text><rect x="385" y="220" width="220" height="130" rx="18" fill="#f0fdf4" stroke="${G}" stroke-width="2"/><text x="495" y="265" text-anchor="middle" class="label green">Produktivitet</text><text x="495" y="320" text-anchor="middle" class="title green">θ</text><rect x="660" y="200" width="240" height="170" rx="20" fill="#fef2f2" stroke="${R}" stroke-width="2"/><text x="780" y="245" text-anchor="middle" class="label red">Teknologivekst</text><text x="780" y="295" text-anchor="middle" class="title red">gA</text><text x="780" y="335" text-anchor="middle" class="small navy">vekst i ideer</text><line x1="345" y1="285" x2="380" y2="285" stroke="${N}" stroke-width="3" marker-end="url(#aromer)"/><line x1="610" y1="285" x2="655" y2="285" stroke="${N}" stroke-width="3" marker-end="url(#aromer)"/><text x="500" y="430" text-anchor="middle" class="small navy">Flere forskere eller bedre forskningsproduktivitet gir raskere teknologivekst.</text>${note(490,'Idéer er ikke-rivaliserende — én gang produsert kan de brukes overalt og gi vedvarende vekst.')}`)}

// === Tilleggsfigurer for vekstregnskap, arbeidsmarked, inflasjon og åpen økonomi ===
const SX={N:'#0f172a',G:'#15803d',R:'#dc2626',B:'#2563eb',O:'#ea580c'};
function sDefs(id){return `<defs><marker id="sx${id}" markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto"><path d="M0 0 L9 4.5 L0 9 Z" fill="${SX.N}"/></marker></defs>`}
function sSvg(s){return `<svg viewBox="0 0 1000 620">${s}</svg>`}
function sHead(t,f){return `<text x="500" y="50" text-anchor="middle" class="title navy">${t}</text><text x="500" y="98" text-anchor="middle" class="formula navy">${f}</text>`}
function sNote(y,t){return `<rect x="70" y="${y}" width="860" height="42" rx="12" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1.5"/><text x="500" y="${y+27}" text-anchor="middle" class="small navy">${t}</text>`}
function sBox(x,y,w,h,c,t,sub){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="14" fill="#fff" stroke="${c}" stroke-width="2"/><text x="${x+w/2}" y="${y+38}" text-anchor="middle" class="label" fill="${c}">${t}</text><text x="${x+w/2}" y="${y+72}" text-anchor="middle" class="small navy">${sub}</text>`}
function fGrowthAccounting(){return sSvg(`${sHead('Vekstregnskap','gY = gA + αgK + (1−α)gL')}<rect x="95" y="210" width="810" height="130" rx="22" fill="#f8fafc" stroke="#cbd5e1" stroke-width="2"/><text x="160" y="285" class="formula navy">gY</text><text x="235" y="285" class="label navy">=</text>${sBox(275,228,150,88,SX.G,'gA','TFP/teknologi')}<text x="450" y="285" class="label navy">+</text>${sBox(485,228,150,88,SX.R,'αgK','kapitalbidrag')}<text x="660" y="285" class="label navy">+</text>${sBox(695,228,165,88,SX.B,'(1−α)gL','arbeidsbidrag')}<path d="M350 370 L350 440 M560 370 L560 440 M780 370 L780 440" stroke="#94a3b8" stroke-width="2" stroke-dasharray="6 6"/><text x="500" y="470" text-anchor="middle" class="label navy">Produksjonsvekst dekomponeres i teknologi + faktorvekst</text>${sNote(535,'Log-derivering gjør eksponentene til vekter i vekstregnskapet.')}`)}
function fURate(){return sSvg(`${sHead('Ledighetsrate','u = U / LF')}<rect x="180" y="190" width="640" height="260" rx="26" fill="#f8fafc" stroke="#cbd5e1" stroke-width="2"/><text x="500" y="235" text-anchor="middle" class="label navy">Andel av arbeidsstyrken som er ledig</text><text x="370" y="335" text-anchor="middle" class="formula red">U</text><line x1="315" y1="352" x2="425" y2="352" stroke="${SX.N}" stroke-width="2"/><text x="370" y="405" text-anchor="middle" class="formula blue">LF</text><text x="560" y="365" class="label navy">= arbeidsledige / arbeidsstyrken</text>${sNote(520,'LF består av både sysselsatte og arbeidsledige. u er en andel, ikke et antall.')}`)}
function fLF(){return sSvg(`${sHead('Arbeidsstyrke','LF = E + U')}<rect x="110" y="245" width="210" height="120" rx="20" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="215" y="294" text-anchor="middle" class="label green">Sysselsatte</text><text x="215" y="334" text-anchor="middle" class="formula green">E</text><text x="365" y="318" text-anchor="middle" class="formula navy">+</text><rect x="410" y="245" width="210" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="515" y="294" text-anchor="middle" class="label red">Arbeidsledige</text><text x="515" y="334" text-anchor="middle" class="formula red">U</text><text x="665" y="318" text-anchor="middle" class="formula navy">=</text><rect x="710" y="245" width="180" height="120" rx="20" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="800" y="294" text-anchor="middle" class="label blue">Arbeidsstyrke</text><text x="800" y="334" text-anchor="middle" class="formula blue">LF</text>${sNote(500,'Arbeidsstyrken er de som enten jobber eller aktivt søker jobb.')}`)}
function fOkun(){return sSvg(`${sDefs('okun')}${sHead('Okuns lov','Ỹ = −β(u − u*)')}<line x1="160" y1="470" x2="850" y2="470" class="axis" marker-end="url(#sxokun)"/><line x1="160" y1="470" x2="160" y2="150" class="axis" marker-end="url(#sxokun)"/><line x1="210" y1="220" x2="790" y2="430" stroke="${SX.B}" stroke-width="4.5"/><line x1="500" y1="155" x2="500" y2="470" stroke="#94a3b8" stroke-width="2" stroke-dasharray="7 7"/><line x1="160" y1="330" x2="850" y2="330" stroke="#94a3b8" stroke-width="2" stroke-dasharray="7 7"/><text x="815" y="515" text-anchor="middle" class="label navy">u − u*</text><text x="112" y="210" text-anchor="middle" class="label navy" transform="rotate(-90 112 210)">Produksjonsgap Ỹ</text><text x="610" y="260" class="label blue">helning = −β</text><text x="260" y="250" class="small green">lav ledighet → positivt gap</text><text x="600" y="430" class="small red">høy ledighet → negativt gap</text>${sNote(545,'Når u er høyere enn u*, blir produksjonsgapet negativt.')}`)}
function fMVPY(){return sSvg(`${sHead('Kvantitetsteorien','M V = P Y')}<rect x="120" y="220" width="310" height="150" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="275" y="270" text-anchor="middle" class="label blue">Pengestrøm</text><text x="275" y="322" text-anchor="middle" class="formula navy">M · V</text><text x="500" y="310" text-anchor="middle" class="formula navy">=</text><rect x="570" y="220" width="310" height="150" rx="22" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="725" y="270" text-anchor="middle" class="label green">Nominelt BNP</text><text x="725" y="322" text-anchor="middle" class="formula navy">P · Y</text>${sNote(505,'Penger brukt i økonomien tilsvarer verdien av produksjonen målt i kroner.')}`)}
function fMVPYGrowth(){return sSvg(`${sHead('Kvantitetsteori i vekstrater','gM + gV = π + gY')}<rect x="100" y="225" width="330" height="145" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="265" y="275" text-anchor="middle" class="label blue">Vekst i pengesiden</text><text x="265" y="325" text-anchor="middle" class="formula navy">gM + gV</text><text x="500" y="315" text-anchor="middle" class="formula navy">=</text><rect x="570" y="225" width="330" height="145" rx="22" fill="#fff7ed" stroke="${SX.O}" stroke-width="2"/><text x="735" y="275" text-anchor="middle" class="label orange">Prisvekst + realvekst</text><text x="735" y="325" text-anchor="middle" class="formula navy">π + gY</text>${sNote(505,'Inflasjon kan ses som pengevekst justert for omløpshastighet og realvekst.')}`)}
function fFisher(){return sSvg(`${sHead('Fisher-ligningen','i ≈ r + πᵉ')}<rect x="110" y="235" width="190" height="120" rx="20" fill="#f8fafc" stroke="${SX.N}" stroke-width="2"/><text x="205" y="285" text-anchor="middle" class="label navy">Nominell</text><text x="205" y="325" text-anchor="middle" class="formula navy">i</text><text x="350" y="315" class="formula navy">≈</text><rect x="410" y="235" width="190" height="120" rx="20" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="505" y="285" text-anchor="middle" class="label green">Realrente</text><text x="505" y="325" text-anchor="middle" class="formula green">r</text><text x="640" y="315" class="formula navy">+</text><rect x="700" y="235" width="210" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="805" y="285" text-anchor="middle" class="label red">Forventet inflasjon</text><text x="805" y="325" text-anchor="middle" class="formula red">πᵉ</text>${sNote(505,'Nominell rente kompenserer både for realavkastning og forventet prisvekst.')}`)}
function fRealRate(){return sSvg(`${sHead('Realrente','r ≈ i − πᵉ')}<rect x="105" y="235" width="190" height="120" rx="20" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="200" y="285" text-anchor="middle" class="label green">Realrente</text><text x="200" y="325" text-anchor="middle" class="formula green">r</text><text x="340" y="315" class="formula navy">≈</text><rect x="405" y="235" width="190" height="120" rx="20" fill="#f8fafc" stroke="${SX.N}" stroke-width="2"/><text x="500" y="285" text-anchor="middle" class="label navy">Nominell rente</text><text x="500" y="325" text-anchor="middle" class="formula navy">i</text><text x="635" y="315" class="formula navy">−</text><rect x="695" y="235" width="220" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="805" y="285" text-anchor="middle" class="label red">Forventet inflasjon</text><text x="805" y="325" text-anchor="middle" class="formula red">πᵉ</text>${sNote(505,'Realrenten er nominell rente justert for forventet inflasjon.')}`)}
function fMPRule(){return sSvg(`${sHead('Pengepolitisk reaksjonsregel','i = r* + π + φπ(π−π*) + φYỸ')}<rect x="70" y="180" width="200" height="120" rx="20" fill="#f8fafc" stroke="${SX.N}" stroke-width="2"/><text x="170" y="225" text-anchor="middle" class="label navy">Nøytral del</text><text x="170" y="265" text-anchor="middle" class="formula navy">r*+π</text><rect x="310" y="180" width="245" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="432" y="225" text-anchor="middle" class="label red">Inflasjonsgap</text><text x="432" y="265" text-anchor="middle" class="formula red">φπ(π−π*)</text><rect x="595" y="180" width="245" height="120" rx="20" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="717" y="225" text-anchor="middle" class="label blue">Produksjonsgap</text><text x="717" y="265" text-anchor="middle" class="formula blue">φYỸ</text><text x="500" y="375" text-anchor="middle" class="formula navy">↓</text><rect x="365" y="410" width="270" height="80" rx="18" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="500" y="462" text-anchor="middle" class="label green">Styringsrente i</text>${sNote(535,'Sentralbanken øker renten når inflasjon eller aktivitet er over mål/normalt nivå.')}`)}
function fRealkurs(){return sSvg(`${sHead('Realvalutakurs','ε = eP* / P')}<rect x="95" y="215" width="250" height="160" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="220" y="275" text-anchor="middle" class="label blue">Utlandet</text><text x="220" y="325" text-anchor="middle" class="formula blue">P*</text><line x1="355" y1="295" x2="625" y2="295" stroke="${SX.N}" stroke-width="2" marker-end="url(#sxrealkurs)"/><text x="490" y="270" text-anchor="middle" class="label navy">gang med e</text><rect x="650" y="215" width="250" height="160" rx="22" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="775" y="275" text-anchor="middle" class="label green">Norge</text><text x="775" y="325" text-anchor="middle" class="formula green">P</text><text x="500" y="430" text-anchor="middle" class="label navy">ε sammenligner utenlandske priser målt i kroner med norske priser.</text>${sNote(515,'Høyere ε betyr relativt dyrere utenlandske varer / svakere realkrone.')}`)}
function fUIP(){return sSvg(`${sHead('Udekket renteparitet','i = i* + forventet depresiering')}<rect x="90" y="210" width="260" height="150" rx="22" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="220" y="265" text-anchor="middle" class="label green">Plasser hjemme</text><text x="220" y="315" text-anchor="middle" class="formula green">i</text><text x="410" y="300" text-anchor="middle" class="formula navy">=</text><rect x="470" y="210" width="360" height="150" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="650" y="258" text-anchor="middle" class="label blue">Plasser ute</text><text x="650" y="308" text-anchor="middle" class="formula blue">i* + Δeᵉ</text><text x="650" y="338" text-anchor="middle" class="small navy">utenlandsk rente + forventet depresiering</text>${sNote(505,'Avkastningen må være lik når investorer fritt kan velge mellom valutaer.')}`)}

const figures={
  // === Nasjonalregnskap ===
  bnp:{title:'BNP etter utgiftsmetoden',sub:'Komponentene som til sammen utgjør BNP.',svg:fBnp},
  nx:{title:'Nettoeksport',sub:'Eksport minus import.',svg:fNx},
  sparing:{title:'Nasjonal sparing',sub:'Det som står igjen etter C og G.',svg:fSparing},
  's-i-nx':{title:'Sparing, investering og nettoeksport',sub:'Sparing fordeles på I og NX.',svg:fSIX},
  // === Vekst og Solow/Romer ===
  cd:{title:'Cobb–Douglas',sub:'Teknologi, kapital og arbeid skaper produksjon.',svg:fCD},
  'per-worker':{title:'Produksjon per arbeider',sub:'Avtakende grenseprodukt av kapital.',svg:fPerWorker},
  'solow-dk':{title:'Solow: kapitalakkumulasjon',sub:'Investering minus break-even-investering.',svg:()=>fSolow('solow-dk')},
  steady:{title:'Solow: steady state',sub:'Der investering akkurat holder kapital per arbeider konstant.',svg:()=>fSolow('steady')},
  'growth-accounting':{title:'Vekstregnskap',sub:'Produksjonsvekst deles i teknologi, kapital og arbeid.',svg:fGrowthAccounting},
  'romer-ga':{title:'Romer-modellen',sub:'Idéer, forskere og teknologivekst.',svg:fRomer},
  // === Arbeidsmarked ===
  'u-rate':{title:'Ledighetsrate',sub:'Arbeidsledige som andel av arbeidsstyrken.',svg:fURate},
  lf:{title:'Arbeidsstyrke',sub:'Sysselsatte pluss arbeidsledige.',svg:fLF},
  'natural-u':{title:'Naturlig ledighet',sub:'Badekarmodellen for inn og ut av ledighet.',svg:fNaturalU},
  okun:{title:'Okuns lov',sub:'Kobler ledighetsgap og produksjonsgap.',svg:fOkun},
  // === Inflasjon og kortsiktig makro ===
  mvpy:{title:'Kvantitetsteorien',sub:'Pengemengde og omløpshastighet mot nominelt BNP.',svg:fMVPY},
  'mvpy-growth':{title:'Kvantitetsteorien i vekstrater',sub:'Pengevekst, omløpshastighet, inflasjon og realvekst.',svg:fMVPYGrowth},
  fisher:{title:'Fisher-ligningen',sub:'Nominell rente, realrente og forventet inflasjon.',svg:fFisher},
  'real-rate':{title:'Realrente',sub:'Nominell rente justert for forventet inflasjon.',svg:fRealRate},
  phillips:{title:'Forventningsutvidet Phillipskurve',sub:'Inflasjon, forventninger og produksjonsgap.',svg:fPhillips},
  'mp-rule':{title:'Pengepolitisk reaksjonsregel',sub:'Hvordan renten reagerer på gap.',svg:fMPRule},
  'is-curve':{title:'IS–MP-likevekt',sub:'Hvordan realrenten bestemmer produksjonsgapet.',svg:fIsMp},
  'ad-curve':{title:'AS–AD-likevekt',sub:'Inflasjon og produksjon i kortsiktig makro.',svg:fAsAd},
  // === Åpen økonomi ===
  realkurs:{title:'Realvalutakurs',sub:'Nominell valutakurs justert for priser.',svg:fRealkurs},
  uip:{title:'Udekket renteparitet',sub:'Hjemlig og utenlandsk forventet avkastning.',svg:fUIP}
};
