const symbolKeys=['π','πᵉ','α','δ','κ','β','λ','ρ','ε','θ','γ','Δ','≈','−','~','^','*'];
const decks=[{id:'all',title:'Alle formler',desc:'Blandet eksamensøving'},{id:'regnskap',title:'Nasjonalregnskap',desc:'BNP, sparing og åpen økonomi'},{id:'vekst',title:'Vekst og Solow/Romer',desc:'Produksjon, kapital og steady state'},{id:'arbeid',title:'Arbeidsmarked',desc:'Ledighet, strømmer og Okun'},{id:'inflasjon',title:'Inflasjon og pengepolitikk',desc:'Fisher, Phillips og kvantitetsteori'},{id:'apen',title:'Åpen økonomi',desc:'Valuta, realkurs og UIP'}];
const cards=[
{id:'bnp',deck:'regnskap',topic:'Nasjonalregnskap',q:'Hvilke komponenter består BNP av etter utgiftsmetoden?',hint:'Fyll inn de fire etterspørselskomponentene.',m:'Y = {{0}} + {{1}} + {{2}} + {{3}}',a:[['C'],['I'],['G'],['NX','X-M','X−M']],answer:'Y = C + I + G + NX',explain:'Utgiftsmetoden summerer privat konsum, investeringer, offentlige kjøp og nettoeksport.',derive:['Samlet etterspørsel etter norsk produksjon består av C, I, G og NX.','Derfor: Y = C + I + G + NX.']},
{id:'nx',deck:'regnskap',topic:'Nasjonalregnskap',q:'Hva er nettoeksport?',hint:'Nettoeksport er eksport minus import.',m:'NX = {{0}} − {{1}}',a:[['X'],['M']],answer:'NX = X − M',explain:'Eksport trekker opp etterspørselen etter norsk produksjon. Import trekkes fra.',derive:['Netto betyr at vi trekker fra det som går motsatt vei.','Derfor: NX = X − M.']},
{id:'sparing',deck:'regnskap',topic:'Sparing',q:'Hva er nasjonal sparing?',hint:'S er det som står igjen når C og G trekkes fra Y.',m:'S = {{0}} − {{1}} − {{2}}',a:[['Y'],['C'],['G']],answer:'S = Y − C − G',explain:'Nasjonal sparing er inntekten som ikke brukes til privat konsum eller offentlige kjøp.',derive:['Start med samlet inntekt Y.','Trekk fra privat konsum C og offentlige kjøp G.','Da står S = Y − C − G igjen.']},
{id:'s-i-nx',deck:'regnskap',topic:'Sparing i åpen økonomi',q:'Hva er sammenhengen mellom sparing, investering og nettoeksport?',hint:'Bruk Y=C+I+G+NX og S=Y−C−G.',m:'S = {{0}} + {{1}}',a:[['I'],['NX','CA']],answer:'S = I + NX',explain:'I åpen økonomi kan sparing finansiere investering hjemme eller netto utlån til utlandet.',derive:['Start: Y = C + I + G + NX.','Flytt C og G til venstre: Y − C − G = I + NX.','Siden S = Y − C − G får vi S = I + NX.']},
{id:'cd',deck:'vekst',topic:'Cobb–Douglas',q:'Hva er Cobb–Douglas-produksjonsfunksjonen?',hint:'Produksjon avhenger av teknologi, kapital og arbeid.',m:'Y = {{0}} <span class="dot">·</span> <span class="pow">{{1}}<sup>{{2}}</sup></span> <span class="dot">·</span> <span class="pow">{{3}}<sup>{{4}}</sup></span>',a:[['A'],['K'],['α','alpha'],['L'],['1−α','1-α','1-alpha','1−alpha']],answer:'Y = A · K^α · L^(1−α)',explain:'α er kapitalens produksjonselastisitet. 1−α er arbeidets elastisitet.',derive:['Kapital får vekt α.','Arbeid får resten av vekten: 1−α.','Teknologinivået A multipliserer hele uttrykket.']},
{id:'per-worker',deck:'vekst',topic:'Per arbeider',q:'Hva er produksjon per arbeider når y=Y/L og k=K/L?',hint:'Del Cobb–Douglas på L.',m:'y = {{0}} <span class="dot">·</span> <span class="pow"><span class="static">k</span><sup>{{1}}</sup></span>',a:[['A'],['α','alpha']],answer:'y = A · k^α',explain:'Y/L = A K^α L^(1−α)/L = A(K/L)^α = A k^α.',derive:['Start med Y = A K^α L^(1−α).','Del på L.','Siden k = K/L får vi y = A k^α.']},
{id:'solow-dk',deck:'vekst',topic:'Kapitalakkumulasjon',q:'Hva er Solow-ligningen for kapital per arbeider?',hint:'Investering per arbeider minus break-even-investering.',m:'Δk = {{0}} <span class="dot">·</span> {{1}} − ({{2}} + {{3}}) <span class="dot">·</span> {{4}}',a:[['s'],['f(k)','y'],['δ','delta'],['n'],['k']],answer:'Δk = s f(k) − (δ+n)k',explain:'Kapital per arbeider øker med sparing/investering og faller når kapital slites eller må fordeles på flere arbeidere.',derive:['Investering per arbeider er s f(k).','Break-even-investering er (δ+n)k.','Netto endring er investering minus break-even-investering.']},
{id:'steady',deck:'vekst',topic:'Steady state',q:'Hva er steady-state-betingelsen i Solow?',hint:'I steady state er Δk = 0.',m:'{{0}} <span class="dot">·</span> {{1}} = ({{2}} + {{3}}) <span class="dot">·</span> <span class="blank star">{{4}}</span>',a:[['s'],['f(k*)','f(k^*)'],['δ','delta'],['n'],['k*','k^*']],answer:'s f(k*) = (δ+n)k*',explain:'Sett Δk=0. Da er investering akkurat lik break-even-investering.',derive:['Start med Δk = s f(k) − (δ+n)k.','I steady state er Δk = 0.','Dermed må s f(k*) = (δ+n)k*.']},
{id:'growth-accounting',deck:'vekst',topic:'Vekstregnskap',q:'Hva er vekstregnskapet fra Cobb–Douglas?',hint:'Log-deriver produksjonsfunksjonen.',m:'gY = {{0}} + {{1}} + ({{2}})<span class="dot">·</span>{{3}}',a:[['gA'],['αgK','α*gK','alpha gK','alphagk'],['1−α','1-α','1-alpha','1−alpha'],['gL']],answer:'gY = gA + αgK + (1−α)gL',explain:'Produksjonsvekst dekomponeres i TFP-vekst og faktorvekster vektet med faktorandeler.',derive:['Ta log av Y = A K^α L^(1−α).','lnY = lnA + αlnK + (1−α)lnL.','Deriver over tid.']},
{id:'u-rate',deck:'arbeid',topic:'Ledighet',q:'Hva er ledighetsraten?',hint:'Arbeidsledige delt på arbeidsstyrken.',m:'u = <span class="frac"><span class="num">{{0}}</span><span class="den">{{1}}</span></span>',a:[['U'],['LF','L']],answer:'u = U / LF',explain:'U er arbeidsledige. LF er arbeidsstyrken.',derive:['Ledighetsraten er andelen av arbeidsstyrken som er arbeidsledig.','Dermed: u = U/LF.']},
{id:'lf',deck:'arbeid',topic:'Arbeidsstyrke',q:'Hva består arbeidsstyrken av?',hint:'Sysselsatte pluss arbeidsledige.',m:'LF = {{0}} + {{1}}',a:[['E','N'],['U']],answer:'LF = E + U',explain:'Arbeidsstyrken er de som enten er i arbeid eller aktivt søker arbeid.',derive:['Arbeidsstyrken består av personer som tilbyr arbeid.','Det inkluderer sysselsatte E og arbeidsledige U.']},
{id:'natural-u',deck:'arbeid',topic:'Naturlig ledighet',q:'Hva er naturlig ledighet i badekarmodellen?',hint:'Separasjoner delt på separasjoner pluss jobbfinning.',m:'u* = {{0}} / ({{1}} + {{2}})',a:[['s'],['s'],['f']],answer:'u* = s / (s+f)',explain:'I steady state er strømmen inn i ledighet lik strømmen ut av ledighet.',derive:['Strøm inn i ledighet: s(1−u).','Strøm ut av ledighet: fu.','Sett likt: s(1−u)=fu → u* = s/(s+f).']},
{id:'okun',deck:'arbeid',topic:'Okuns lov',q:'Skriv en enkel Okun-sammenheng.',hint:'Høyere ledighet enn naturlig ledighet gir negativt produksjonsgap.',m:'<span class="blank tilde">{{0}}</span> = −{{1}}({{2}} − <span class="blank star">{{3}}</span>)',a:[['Y~','y~','Ytilde'],['β','beta'],['u'],['u*','u^*']],answer:'Ỹ = −β(u − u*)',explain:'Okuns lov kobler produksjonsgap til avvik mellom faktisk og naturlig ledighet.',derive:['Hvis u > u*, er produksjonsgapet negativt.','Dette fanges av minusfortegnet i Ỹ = −β(u−u*).']},
{id:'mvpy',deck:'inflasjon',topic:'Kvantitetsteori',q:'Hva er kvantitetsteorien?',hint:'Penger ganger omløpshastighet er lik nominelt BNP.',m:'{{0}}<span class="dot">·</span>{{1}} = {{2}}<span class="dot">·</span>{{3}}',a:[['M'],['V'],['P'],['Y']],answer:'M V = P Y',explain:'MV tilsvarer nominelt BNP, PY.',derive:['MV måler hvor mye penger som brukes i transaksjoner.','PY er nominelt BNP.']},
{id:'mvpy-growth',deck:'inflasjon',topic:'Kvantitetsteori i vekstrater',q:'Hva blir kvantitetsteorien i vekstrater?',hint:'Ta vekstrater på begge sider av MV=PY.',m:'gM + gV = {{0}} + {{1}}',a:[['π','pi'],['gY']],answer:'gM + gV = π + gY',explain:'Siden vekst i P er inflasjon, får vi π = gM + gV − gY.',derive:['Start fra MV = PY.','Ta vekstrate: gM + gV = gP + gY.','Siden gP = π får du uttrykket.']},
{id:'fisher',deck:'inflasjon',topic:'Fisher',q:'Hva er Fisher-ligningen?',hint:'Nominell rente er omtrent realrente pluss forventet inflasjon.',m:'i ≈ {{0}} + {{1}}',a:[['r'],['πe','π^e','πᵉ','pi^e']],answer:'i ≈ r + πᵉ',explain:'Fisher skiller nominell rente fra realrente.',derive:['Eksakt: 1+i = (1+r)(1+πᵉ).','For små rater brukes tilnærmingen i ≈ r + πᵉ.']},
{id:'real-rate',deck:'inflasjon',topic:'Realrente',q:'Hvordan finner du realrenten omtrent?',hint:'Omorganiser Fisher-ligningen.',m:'r ≈ {{0}} − {{1}}',a:[['i'],['πe','π^e','πᵉ','pi^e']],answer:'r ≈ i − πᵉ',explain:'Realrenten er nominell rente justert for forventet inflasjon.',derive:['Start med Fisher: i ≈ r + πᵉ.','Trekk πᵉ fra begge sider.']},
{id:'phillips',deck:'inflasjon',topic:'Phillipskurve',q:'Skriv en enkel forventningsutvidet Phillipskurve.',hint:'Inflasjon avhenger av forventet inflasjon og produksjonsgap.',m:'π = {{0}} + {{1}}<span class="dot">·</span><span class="blank tilde">{{2}}</span>',a:[['πe','π^e','πᵉ','pi^e'],['κ','kappa'],['Y~','y~','Ytilde']],answer:'π = πᵉ + κỸ',explain:'Når produksjonen er over potensielt nivå, øker inflasjonspresset.',derive:['Forventet inflasjon danner utgangspunktet.','Et positivt produksjonsgap legges til som κỸ.']},
{id:'mp-rule',deck:'inflasjon',topic:'Taylor/MP-regel',q:'Skriv en enkel pengepolitisk reaksjonsregel.',hint:'Renten reagerer på inflasjonsgap og produksjonsgap.',m:'i = <span class="blank star">{{0}}</span> + {{1}} + {{2}}({{3}}−<span class="blank star">{{4}}</span>) + {{5}}<span class="dot">·</span><span class="blank tilde">{{6}}</span>',a:[['r*','r^*'],['π'],['φπ','phiπ'],['π'],['π*','π^*'],['φY','phiy','phiY'],['Y~','y~','Ytilde']],answer:'i = r* + π + φπ(π−π*) + φYỸ',explain:'Pengepolitikken hever renten når inflasjonen eller produksjonen ligger over mål/normalt nivå.',derive:['Nøytral nominell rente er r* + π.','Legg til respons på inflasjonsgapet og produksjonsgapet.']},
{id:'realkurs',deck:'apen',topic:'Realkurs',q:'Hva er realvalutakursen?',hint:'Nominell valutakurs justert for prisnivå hjemme og ute.',m:'ε = {{0}} <span class="dot">·</span> {{1}} / {{2}}',a:[['e'],['P*','P^*'],['P']],answer:'ε = eP*/P',explain:'Realkursen måler relativ pris på utenlandske varer målt i innenlandske varer.',derive:['Ta nominell valutakurs e.','Multipliser med utenlandsk prisnivå P*.','Del på innenlandsk prisnivå P.']},
{id:'uip',deck:'apen',topic:'UIP',q:'Hva er udekket renteparitet i enkel form?',hint:'Innenlandsk rente følger utenlandsk rente pluss forventet depresiering.',m:'i = <span class="blank star">{{0}}</span> + {{1}}',a:[['i*','i^*'],['Δeᵉ','de','expected depreciation']],answer:'i = i* + forventet depresiering',explain:'Investorer krever kompensasjon hvis valutaen forventes å svekke seg.',derive:['Avkastningen hjemme må tilsvare forventet avkastning ute.','Hvis hjemlig valuta forventes å svekke seg, må i være høyere.']}
];
