const $=id=>document.getElementById(id);let deck='all',idx=0,answered=false,currentFocus=null,round=[];
const norm=s=>(s||'').toString().trim().replace(/\s+/g,'').replace(/−/g,'-').replace(/ᵉ/g,'e').replace(/\*/g,'').replace(/-/g,'').toLowerCase();
const filtered=()=>deck==='all'?cards:cards.filter(c=>c.deck===deck);
function renderDecks(){deckList.innerHTML=decks.map(d=>`<button class="deckbtn ${deck===d.id?'active':''}" data-id="${d.id}"><b>${d.title}</b><span>${d.desc}</span></button>`).join('');document.querySelectorAll('.deckbtn').forEach(b=>b.onclick=()=>{deck=b.dataset.id;idx=0;answered=false;feedback.className='feedback';feedback.innerHTML='';summary.className='summary';render();});}
function renderPad(){symbolPad.innerHTML=symbolKeys.map(k=>`<button class="key" type="button">${k}</button>`).join('');symbolPad.querySelectorAll('.key').forEach(k=>k.onclick=()=>{const input=currentFocus||formulaBox.querySelector('input');if(!input)return;input.focus();const s=input.selectionStart||0;input.value=input.value.slice(0,s)+k.textContent+input.value.slice(input.selectionEnd||s);input.dispatchEvent(new Event('input'));input.setSelectionRange(s+k.textContent.length,s+k.textContent.length);});}
function makeFormula(c){let html=c.m.replace(/{{(\d+)}}/g,(m,n)=>`<span class="blank"><input data-i="${n}" autocomplete="off"></span>`);formulaBox.innerHTML=html;const inputs=[...formulaBox.querySelectorAll('input')];inputs.forEach((inp,i)=>{inp.onfocus=()=>currentFocus=inp;inp.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();(inputs[i+1]||inputs[0]).focus();}if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();(inputs[i-1]||inputs[inputs.length-1]).focus();}if(e.key==='Enter'){e.preventDefault();if(answered)next();else check();}}});setTimeout(()=>inputs[0]?.focus(),60);}
function render(){const arr=filtered(),c=arr[idx];if(!c)return;answered=false;deckTitle.textContent=decks.find(d=>d.id===deck)?.title||'Alle formler';counter.textContent=`${idx+1} / ${arr.length}`;bar.style.width=`${((idx+1)/arr.length)*100}%`;topic.textContent=c.topic;question.textContent=c.q;hint.textContent=c.hint;makeFormula(c);figureBtn.disabled=!figures[c.id];feedback.className='feedback';feedback.innerHTML='';renderStats();}
function check(){const c=filtered()[idx];const inputs=[...formulaBox.querySelectorAll('input')];let ok=true;inputs.forEach((inp,i)=>{const valid=(c.a[i]||[]).map(norm).includes(norm(inp.value));inp.classList.toggle('correct',valid);inp.classList.toggle('wrong',!valid);if(!valid)ok=false;});answered=true;round.push({id:c.id,q:c.q,answer:c.answer,ok,shown:false,topic:c.topic});feedback.className='feedback '+(ok?'good':'bad');feedback.innerHTML=`<h3>${ok?'Riktig':'Ikke helt riktig'}</h3><p>${c.explain}</p><div class="answer">${c.answer}</div>${derive(c)}<div class="enterHint">Trykk Enter for neste spørsmål.</div>`;renderStats();}
function derive(c){return `<div class="deriveBox"><b>Utledning / logikk</b>${(c.derive||[]).map(x=>`<p>${x}</p>`).join('')}</div>`;}
function showAnswer(){const c=filtered()[idx];answered=true;round.push({id:c.id,q:c.q,answer:c.answer,ok:false,shown:true,topic:c.topic});feedback.className='feedback bad';feedback.innerHTML=`<h3>Riktig svar</h3><p>${c.explain}</p><div class="answer">${c.answer}</div>${derive(c)}<div class="enterHint">Trykk Enter for neste spørsmål.</div>`;renderStats();}
function next(){const arr=filtered();idx=(idx+1)%arr.length;render();}
function prev(){const arr=filtered();idx=(idx-1+arr.length)%arr.length;render();}
function renderStats(){const total=cards.length,right=round.filter(r=>r.ok).length,attempts=round.length;statTotal.textContent=total;statRight.textContent=right;statPct.textContent=attempts?Math.round(100*right/attempts)+'%':'0%';}
function finishRound(){const attempts=round.length,right=round.filter(r=>r.ok).length,shown=round.filter(r=>r.shown).length,wrong=attempts-right-shown;const weak=[...new Set(round.filter(r=>!r.ok).map(r=>r.topic))];summary.className='summary show';summary.innerHTML=`<div class="summaryCard"><h2>Oppsummering av runden</h2><div class="summaryGrid"><div class="summaryStat"><b>${attempts}</b><span>Besvart</span></div><div class="summaryStat"><b>${right}</b><span>Riktig</span></div><div class="summaryStat"><b>${wrong}</b><span>Feil</span></div><div class="summaryStat"><b>${shown}</b><span>Vist fasit</span></div></div><p style="font-size:13px;color:#64748b">Jobb mer med: ${weak.length?weak.join(', '):'ingen tydelige svake områder i denne runden'}.</p><div class="summaryList">${round.map(r=>`<div class="summaryItem ${r.ok?'good':r.shown?'shown':'bad'}"><b>${r.ok?'✅':r.shown?'👁️':'❌'} ${r.q}</b><p>${r.answer}</p></div>`).join('')}</div><button class="btn primary" style="margin-top:12px" onclick="round=[];summary.className='summary';renderStats()">Start ny runde</button></div>`;summary.scrollIntoView({behavior:'smooth',block:'start'});}
function symbolQuizHtml(id){const q=(typeof symbolQuiz!=='undefined'&&symbolQuiz[id])?symbolQuiz[id]:null;if(!q)return '<div class="symbolQuiz"><h3>Symbolquiz</h3><p>Symbolfasit er ikke lagt inn for denne formelen ennå.</p></div>';return `<div class="symbolQuiz" data-formula="${id}"><div class="symbolQuizHead"><div><h3>Øv på symbolene</h3><p>Hva står hvert symbol for i formelen?</p></div><div class="symbolFormula">${q.formula}</div></div><div class="symbolRows">${q.items.map((it,i)=>`<label class="symbolRow"><span>${it[0]} =</span><input data-i="${i}" placeholder="Skriv betydningen ..." autocomplete="off"></label>`).join('')}</div><div class="symbolActions"><button class="btn primary" type="button" onclick="checkSymbolQuiz('${id}')">Sjekk symboler</button><button class="btn secondary" type="button" onclick="showSymbolAnswers('${id}')">Vis fasit</button></div><div class="symbolFeedback" id="symbolFeedback"></div></div>`;}
function checkSymbolQuiz(id){const q=symbolQuiz[id];if(!q)return;let ok=0;document.querySelectorAll('.symbolRow').forEach((row,i)=>{const inp=row.querySelector('input');const good=q.items[i][1].some(a=>norm(inp.value).includes(norm(a))||norm(a).includes(norm(inp.value)));row.classList.toggle('ok',good);row.classList.toggle('bad',!good);if(good)ok++;});const fb=document.getElementById('symbolFeedback');fb.className='symbolFeedback show';fb.innerHTML=`<b>${ok} av ${q.items.length} riktige</b><p>${ok===q.items.length?'Sterkt — du kobler symbolene til økonomisk mening.':'Se over de røde feltene, eller vis fasit og prøv igjen senere.'}</p>`;}
function showSymbolAnswers(id){const q=symbolQuiz[id];if(!q)return;const fb=document.getElementById('symbolFeedback');fb.className='symbolFeedback show';fb.innerHTML=`<b>Fasit</b><div class="symbolAnswerGrid">${q.items.map(it=>`<div><span>${it[0]}</span><p>${it[1][0]}</p></div>`).join('')}</div>`;}
function openFigure(){const c=filtered()[idx],f=figures[c.id];if(!f)return;figureTitle.textContent=f.title;figureSub.textContent=f.sub;figureStage.innerHTML=f.svg()+symbolQuizHtml(c.id);figureOverlay.classList.add('show');setTimeout(()=>figureStage.querySelector('.symbolRow input')?.focus(),150);}
function closeFigure(){figureOverlay.classList.remove('show');}
checkBtn.onclick=check;showBtn.onclick=showAnswer;nextBtn.onclick=next;prevBtn.onclick=prev;finishBtn.onclick=finishRound;figureBtn.onclick=openFigure;closeFig.onclick=closeFigure;figureOverlay.onclick=e=>{if(e.target===figureOverlay)closeFigure();};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFigure();});renderDecks();renderPad();render();
