const SX={N:'#0f172a',G:'#15803d',R:'#dc2626',B:'#2563eb',O:'#ea580c'};
function sDefs(id){return `<defs><marker id="sx${id}" markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto"><path d="M0 0 L9 4.5 L0 9 Z" fill="${SX.N}"/></marker></defs>`}
function sSvg(s){return `<svg viewBox="0 0 1000 620">${s}</svg>`}
function sHead(t,f){return `<text x="500" y="50" text-anchor="middle" class="title navy">${t}</text><text x="500" y="98" text-anchor="middle" class="formula navy">${f}</text>`}
function sNote(y,t){return `<rect x="70" y="${y}" width="860" height="42" rx="12" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1.5"/><text x="500" y="${y+27}" text-anchor="middle" class="small navy">${t}</text>`}
function sBox(x,y,w,h,c,t,sub){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="14" fill="#fff" stroke="${c}" stroke-width="2"/><text x="${x+w/2}" y="${y+38}" text-anchor="middle" class="label" fill="${c}">${t}</text><text x="${x+w/2}" y="${y+72}" text-anchor="middle" class="small navy">${sub}</text>`}
function fGrowthAccounting(){return sSvg(`${sHead('Vekstregnskap','gY = gA + αgK + (1−α)gL')}<rect x="95" y="210" width="810" height="130" rx="22" fill="#f8fafc" stroke="#cbd5e1" stroke-width="2"/><text x="160" y="285" class="formula navy">gY</text><text x="235" y="285" class="label navy">=</text>${sBox(275,228,150,88,SX.G,'gA','TFP/teknologi')}<text x="450" y="285" class="label navy">+</text>${sBox(485,228,150,88,SX.R,'αgK','kapitalbidrag')}<text x="660" y="285" class="label navy">+</text>${sBox(695,228,165,88,SX.B,'(1−α)gL','arbeidsbidrag')}<path d="M350 370 L350 440 M560 370 L560 440 M780 370 L780 440" stroke="#94a3b8" stroke-width="2" stroke-dasharray="6 6"/><text x="500" y="470" text-anchor="middle" class="label navy">Produksjonsvekst dekomponeres i teknologi + faktorvekst</text>${sNote(535,'Log-derivering gjør eksponentene til vekter i vekstregnskapet.')}`)}
function fURate(){return sSvg(`${sHead('Ledighetsrate','u = U / LF')}<rect x="180" y="190" width="640" height="260" rx="26" fill="#f8fafc" stroke="#cbd5e1" stroke-width="2"/><text x="500" y="235" text-anchor="middle" class="label navy">Andel av arbeidsstyrken som er ledig</text><text x="370" y="335" text-anchor="middle" class="formula red">U</text><line x1="315" y1="352" x2="425" y2="352" stroke="${SX.N}" stroke-width="2"/><text x="370" y="405" text-anchor="middle" class="formula blue">LF</text><text x="560" y="365" class="label navy">= arbeidsledige / arbeidsstyrken</text>${sNote(520,'LF består av både sysselsatte og arbeidsledige. u er en andel, ikke et antall.')}`)}
function fLF(){return sSvg(`${sHead('Arbeidsstyrke','LF = E + U')}<rect x="110" y="245" width="210" height="120" rx="20" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="215" y="294" text-anchor="middle" class="label green">Sysselsatte</text><text x="215" y="334" text-anchor="middle" class="formula green">E</text><text x="365" y="318" text-anchor="middle" class="formula navy">+</text><rect x="410" y="245" width="210" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="515" y="294" text-anchor="middle" class="label red">Arbeidsledige</text><text x="515" y="334" text-anchor="middle" class="formula red">U</text><text x="665" y="318" text-anchor="middle" class="formula navy">=</text><rect x="710" y="245" width="180" height="120" rx="20" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="800" y="294" text-anchor="middle" class="label blue">Arbeidsstyrke</text><text x="800" y="334" text-anchor="middle" class="formula blue">LF</text>${sNote(500,'Arbeidsstyrken er de som enten jobber eller aktivt søker jobb.')}`)}
function fOkun(){return sSvg(`${sDefs('okun')}${sHead('Okuns lov','Ỹ = −β(u − u*)')}<line x1="160" y1="470" x2="850" y2="470" class="axis" marker-end="url(#sxokun)"/><line x1="160" y1="470" x2="160" y2="150" class="axis" marker-end="url(#sxokun)"/><line x1="210" y1="220" x2="790" y2="430" stroke="${SX.B}" stroke-width="4.5"/><line x1="500" y1="155" x2="500" y2="470" stroke="#94a3b8" stroke-width="2" stroke-dasharray="7 7"/><line x1="160" y1="330" x2="850" y2="330" stroke="#94a3b8" stroke-width="2" stroke-dasharray="7 7"/><text x="815" y="515" text-anchor="middle" class="label navy">u − u*</text><text x="112" y="210" text-anchor="middle" class="label navy" transform="rotate(-90 112 210)">Produksjonsgap Ỹ</text><text x="610" y="260" class="label blue">helning = −β</text><text x="260" y="250" class="small green">lav ledighet → positivt gap</text><text x="600" y="430" class="small red">høy ledighet → negativt gap</text>${sNote(545,'Når u er høyere enn u*, blir produksjonsgapet negativt.')}`)}
function fMVPY(){return sSvg(`${sHead('Kvantitetsteorien','M V = P Y')}<rect x="120" y="220" width="310" height="150" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="275" y="270" text-anchor="middle" class="label blue">Pengestrøm</text><text x="275" y="322" text-anchor="middle" class="formula navy">M · V</text><text x="500" y="310" text-anchor="middle" class="formula navy">=</text><rect x="570" y="220" width="310" height="150" rx="22" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="725" y="270" text-anchor="middle" class="label green">Nominelt BNP</text><text x="725" y="322" text-anchor="middle" class="formula navy">P · Y</text>${sNote(505,'Penger brukt i økonomien tilsvarer verdien av produksjonen målt i kroner.')}`)}
function fMVPYGrowth(){return sSvg(`${sHead('Kvantitetsteori i vekstrater','gM + gV = π + gY')}<rect x="100" y="225" width="330" height="145" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="265" y="275" text-anchor="middle" class="label blue">Vekst i pengesiden</text><text x="265" y="325" text-anchor="middle" class="formula navy">gM + gV</text><text x="500" y="315" text-anchor="middle" class="formula navy">=</text><rect x="570" y="225" width="330" height="145" rx="22" fill="#fff7ed" stroke="${SX.O}" stroke-width="2"/><text x="735" y="275" text-anchor="middle" class="label orange">Prisvekst + realvekst</text><text x="735" y="325" text-anchor="middle" class="formula navy">π + gY</text>${sNote(505,'Inflasjon kan ses som pengevekst justert for omløpshastighet og realvekst.')}`)}
function fFisher(){return sSvg(`${sHead('Fisher-ligningen','i ≈ r + πᵉ')}<rect x="110" y="235" width="190" height="120" rx="20" fill="#f8fafc" stroke="${SX.N}" stroke-width="2"/><text x="205" y="285" text-anchor="middle" class="label navy">Nominell</text><text x="205" y="325" text-anchor="middle" class="formula navy">i</text><text x="350" y="315" class="formula navy">≈</text><rect x="410" y="235" width="190" height="120" rx="20" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="505" y="285" text-anchor="middle" class="label green">Realrente</text><text x="505" y="325" text-anchor="middle" class="formula green">r</text><text x="640" y="315" class="formula navy">+</text><rect x="700" y="235" width="210" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="805" y="285" text-anchor="middle" class="label red">Forventet inflasjon</text><text x="805" y="325" text-anchor="middle" class="formula red">πᵉ</text>${sNote(505,'Nominell rente kompenserer både for realavkastning og forventet prisvekst.')}`)}
function fRealRate(){return sSvg(`${sHead('Realrente','r ≈ i − πᵉ')}<rect x="105" y="235" width="190" height="120" rx="20" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="200" y="285" text-anchor="middle" class="label green">Realrente</text><text x="200" y="325" text-anchor="middle" class="formula green">r</text><text x="340" y="315" class="formula navy">≈</text><rect x="405" y="235" width="190" height="120" rx="20" fill="#f8fafc" stroke="${SX.N}" stroke-width="2"/><text x="500" y="285" text-anchor="middle" class="label navy">Nominell rente</text><text x="500" y="325" text-anchor="middle" class="formula navy">i</text><text x="635" y="315" class="formula navy">−</text><rect x="695" y="235" width="220" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="805" y="285" text-anchor="middle" class="label red">Forventet inflasjon</text><text x="805" y="325" text-anchor="middle" class="formula red">πᵉ</text>${sNote(505,'Realrenten er nominell rente justert for forventet inflasjon.')}`)}
function fMPRule(){return sSvg(`${sHead('Pengepolitisk reaksjonsregel','i = r* + π + φπ(π−π*) + φYỸ')}<rect x="70" y="180" width="200" height="120" rx="20" fill="#f8fafc" stroke="${SX.N}" stroke-width="2"/><text x="170" y="225" text-anchor="middle" class="label navy">Nøytral del</text><text x="170" y="265" text-anchor="middle" class="formula navy">r*+π</text><rect x="310" y="180" width="245" height="120" rx="20" fill="#fef2f2" stroke="${SX.R}" stroke-width="2"/><text x="432" y="225" text-anchor="middle" class="label red">Inflasjonsgap</text><text x="432" y="265" text-anchor="middle" class="formula red">φπ(π−π*)</text><rect x="595" y="180" width="245" height="120" rx="20" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="717" y="225" text-anchor="middle" class="label blue">Produksjonsgap</text><text x="717" y="265" text-anchor="middle" class="formula blue">φYỸ</text><text x="500" y="375" text-anchor="middle" class="formula navy">↓</text><rect x="365" y="410" width="270" height="80" rx="18" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="500" y="462" text-anchor="middle" class="label green">Styringsrente i</text>${sNote(535,'Sentralbanken øker renten når inflasjon eller aktivitet er over mål/normalt nivå.')}`)}
function fRealkurs(){return sSvg(`${sHead('Realvalutakurs','ε = eP* / P')}<rect x="95" y="215" width="250" height="160" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="220" y="275" text-anchor="middle" class="label blue">Utlandet</text><text x="220" y="325" text-anchor="middle" class="formula blue">P*</text><line x1="355" y1="295" x2="625" y2="295" stroke="${SX.N}" stroke-width="2" marker-end="url(#sxrealkurs)"/><text x="490" y="270" text-anchor="middle" class="label navy">gang med e</text><rect x="650" y="215" width="250" height="160" rx="22" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="775" y="275" text-anchor="middle" class="label green">Norge</text><text x="775" y="325" text-anchor="middle" class="formula green">P</text><text x="500" y="430" text-anchor="middle" class="label navy">ε sammenligner utenlandske priser målt i kroner med norske priser.</text>${sNote(515,'Høyere ε betyr relativt dyrere utenlandske varer / svakere realkrone.')}`)}
function fUIP(){return sSvg(`${sHead('Udekket renteparitet','i = i* + forventet depresiering')}<rect x="90" y="210" width="260" height="150" rx="22" fill="#f0fdf4" stroke="${SX.G}" stroke-width="2"/><text x="220" y="265" text-anchor="middle" class="label green">Plasser hjemme</text><text x="220" y="315" text-anchor="middle" class="formula green">i</text><text x="410" y="300" text-anchor="middle" class="formula navy">=</text><rect x="470" y="210" width="360" height="150" rx="22" fill="#eff6ff" stroke="${SX.B}" stroke-width="2"/><text x="650" y="258" text-anchor="middle" class="label blue">Plasser ute</text><text x="650" y="308" text-anchor="middle" class="formula blue">i* + Δeᵉ</text><text x="650" y="338" text-anchor="middle" class="small navy">utenlandsk rente + forventet depresiering</text>${sNote(505,'Avkastningen må være lik når investorer fritt kan velge mellom valutaer.')}`)}
Object.assign(figures,{
'growth-accounting':{title:'Vekstregnskap',sub:'Produksjonsvekst deles i teknologi, kapital og arbeid.',svg:fGrowthAccounting},
'u-rate':{title:'Ledighetsrate',sub:'Arbeidsledige som andel av arbeidsstyrken.',svg:fURate},
lf:{title:'Arbeidsstyrke',sub:'Sysselsatte pluss arbeidsledige.',svg:fLF},
okun:{title:'Okuns lov',sub:'Kobler ledighetsgap og produksjonsgap.',svg:fOkun},
mvpy:{title:'Kvantitetsteorien',sub:'Pengemengde og omløpshastighet mot nominelt BNP.',svg:fMVPY},
'mvpy-growth':{title:'Kvantitetsteorien i vekstrater',sub:'Pengevekst, omløpshastighet, inflasjon og realvekst.',svg:fMVPYGrowth},
fisher:{title:'Fisher-ligningen',sub:'Nominell rente, realrente og forventet inflasjon.',svg:fFisher},
'real-rate':{title:'Realrente',sub:'Nominell rente justert for forventet inflasjon.',svg:fRealRate},
'mp-rule':{title:'Pengepolitisk reaksjonsregel',sub:'Hvordan renten reagerer på gap.',svg:fMPRule},
realkurs:{title:'Realvalutakurs',sub:'Nominell valutakurs justert for priser.',svg:fRealkurs},
uip:{title:'Udekket renteparitet',sub:'Hjemlig og utenlandsk forventet avkastning.',svg:fUIP}
});
const symbolQuiz={
bnp:{formula:'Y = C + I + G + NX',items:[['Y',['bnp','produksjon','bruttonasjonalprodukt']],['C',['konsum','privat konsum','husholdningenes konsum']],['I',['investering','investeringer']],['G',['offentlig','offentlige kjøp','offentlig konsum','stat']],['NX',['nettoeksport','eksport minus import']]]},
nx:{formula:'NX = X − M',items:[['NX',['nettoeksport']],['X',['eksport']],['M',['import']]]},
sparing:{formula:'S = Y − C − G',items:[['S',['sparing','nasjonal sparing']],['Y',['bnp','inntekt','produksjon']],['C',['konsum','privat konsum']],['G',['offentlig kjøp','offentlig','stat']]]},
's-i-nx':{formula:'S = I + NX',items:[['S',['sparing','nasjonal sparing']],['I',['investering','investeringer']],['NX',['nettoeksport','eksport minus import']]]},
cd:{formula:'Y = A K^α L^(1−α)',items:[['Y',['produksjon','bnp']],['A',['teknologi','total faktorproduktivitet','tfp']],['K',['kapital']],['L',['arbeid','arbeidskraft']],['α',['kapitalens vekt','kapitalandel','kapitalens elastisitet']],['1−α',['arbeidets vekt','arbeidsandel','arbeidets elastisitet']]]},
'per-worker':{formula:'y = A k^α',items:[['y',['produksjon per arbeider']],['A',['teknologi','tfp']],['k',['kapital per arbeider']],['α',['kapitalens vekt','kapitalandel']]]},
'solow-dk':{formula:'Δk = s f(k) − (δ+n)k',items:[['Δk',['endring i kapital per arbeider']],['s',['sparerate','sparing']],['f(k)',['produksjon per arbeider']],['δ',['kapitalslit','depresiering']],['n',['befolkningsvekst','arbeidsstyrkevekst']],['k',['kapital per arbeider']]]},
steady:{formula:'s f(k*) = (δ+n)k*',items:[['k*',['steady state kapital','langsiktig kapital']],['s',['sparerate']],['δ',['kapitalslit','depresiering']],['n',['befolkningsvekst']],['f(k*)',['produksjon i steady state']]]},
'growth-accounting':{formula:'gY = gA + αgK + (1−α)gL',items:[['gY',['produksjonsvekst','bnp-vekst']],['gA',['tfp-vekst','teknologivekst']],['gK',['kapitalvekst']],['gL',['arbeidsvekst','vekst i arbeid']],['α',['kapitalandel','kapitalens vekt']]]},
'u-rate':{formula:'u = U / LF',items:[['u',['ledighetsrate']],['U',['arbeidsledige','ledige']],['LF',['arbeidsstyrke']]]},
lf:{formula:'LF = E + U',items:[['LF',['arbeidsstyrke']],['E',['sysselsatte','sysselsetting']],['U',['arbeidsledige','ledige']]]},
'natural-u':{formula:'u* = s/(s+f)',items:[['u*',['naturlig ledighet','naturlig ledighetsrate']],['s',['separasjonsrate','separasjoner']],['f',['jobbfinning','jobbfinningrate','jobbfinningrate']]]},
okun:{formula:'Ỹ = −β(u−u*)',items:[['Ỹ',['produksjonsgap']],['β',['okun-koeffisient','følsomhet']],['u',['ledighet','ledighetsrate']],['u*',['naturlig ledighet']]]},
mvpy:{formula:'M V = P Y',items:[['M',['pengemengde']],['V',['omløpshastighet']],['P',['prisnivå']],['Y',['realproduksjon','real bnp']]]},
'mvpy-growth':{formula:'gM + gV = π + gY',items:[['gM',['pengevekst','vekst i pengemengde']],['gV',['vekst i omløpshastighet']],['π',['inflasjon','prisvekst']],['gY',['realvekst','produksjonsvekst']]]},
fisher:{formula:'i ≈ r + πᵉ',items:[['i',['nominell rente']],['r',['realrente']],['πᵉ',['forventet inflasjon']]]},
'real-rate':{formula:'r ≈ i − πᵉ',items:[['r',['realrente']],['i',['nominell rente']],['πᵉ',['forventet inflasjon']]]},
phillips:{formula:'π = πᵉ + κỸ',items:[['π',['inflasjon']],['πᵉ',['forventet inflasjon']],['κ',['følsomhet','respons']],['Ỹ',['produksjonsgap']]]},
'mp-rule':{formula:'i = r* + π + φπ(π−π*) + φYỸ',items:[['i',['styringsrente','nominell rente']],['r*',['nøytral realrente']],['π',['inflasjon']],['π*',['inflasjonsmål']],['φπ',['respons på inflasjon']],['φY',['respons på produksjonsgap']],['Ỹ',['produksjonsgap']]]},
realkurs:{formula:'ε = eP*/P',items:[['ε',['realvalutakurs','realkurs']],['e',['nominell valutakurs']],['P*',['utenlandsk prisnivå']],['P',['innenlandsk prisnivå','norsk prisnivå']]]},
uip:{formula:'i = i* + forventet depresiering',items:[['i',['innenlandsk rente','norsk rente']],['i*',['utenlandsk rente']],['Δeᵉ',['forventet depresiering','forventet svekkelse']]]},
'is-curve':{formula:'Ỹ = −α(r − r*)',items:[['Ỹ',['produksjonsgap']],['α',['rentefølsomhet','rentesensitivitet','følsomhet']],['r',['realrente']],['r*',['nøytral realrente','naturlig realrente']]]},
'ad-curve':{formula:'Ỹ = −γ(π − π*)',items:[['Ỹ',['produksjonsgap']],['γ',['følsomhet','respons']],['π',['inflasjon']],['π*',['inflasjonsmål']]]},
'romer-ideas':{formula:'gA = θ · Lₐ',items:[['gA',['teknologivekst','vekst i teknologi','vekstrate teknologi']],['θ',['forskningsproduktivitet','produktivitet','idéproduktivitet']],['Lₐ',['forskere','arbeidskraft i forskning','arbeid i fou','antall forskere']]]}
};
