// Generated by scripts/generate-learning-content.mjs. Edit data/learning-content.json instead.
(function (window) {
  'use strict';

  var payload = {
  "data": {
    "version": "2026.07-platform-v1",
    "updatedAt": "2026-07-02",
    "subjects": [
      {
        "id": "ret14",
        "code": "RET14",
        "name": "Skatterett",
        "accent": "#2f62ff",
        "priority": 1,
        "stage": "rich",
        "lead": "Skatt, fradrag, aksjer, personinntekt, arv, lovhjemler og eksamensanalyse.",
        "sourceSummary": "Stort lokalt grunnlag med forelesninger, eksamener, sensorveiledninger og A-besvarelser.",
        "defaultHref": "../ret14/",
        "flashcardsHref": "../flashcards/?subject=ret14"
      },
      {
        "id": "subj_sol1",
        "code": "SOL1",
        "name": "Organisasjonsatferd",
        "accent": "#20b97a",
        "priority": 1,
        "stage": "rich",
        "lead": "Begreper, teorier, modeller, caseforståelse og teoriskriving.",
        "sourceSummary": "Sterkt strukturert fag med forelesningsnotater, kompendium, case og eksisterende kortpakker.",
        "defaultHref": "../sol1/",
        "flashcardsHref": "../flashcards/?subject=subj_sol1"
      },
      {
        "id": "sam3",
        "code": "SAM3",
        "name": "Makroøkonomi",
        "accent": "#ef4444",
        "priority": 1,
        "stage": "rich",
        "lead": "Makromodeller, formler, quiz, eksamensradar, mock-eksamen og modellforklaring.",
        "sourceSummary": "Svært stort Canvas-grunnlag med forelesninger, eksamenssett, sensorveiledninger og A-besvarelser.",
        "defaultHref": "../sam3/",
        "flashcardsHref": "../sam3/flashcards.html"
      },
      {
        "id": "mat10",
        "code": "MAT10",
        "name": "Matematikk",
        "accent": "#0891b2",
        "priority": 1,
        "stage": "ready_for_import",
        "lead": "Analyse, lineær algebra, formler, regneøkter og eksamensdrill.",
        "sourceSummary": "Komplett lokal Canvas-eksport med kompendium og mange sensorveiledninger.",
        "defaultHref": "../mat10/",
        "flashcardsHref": "../flashcards/?subject=mat10"
      },
      {
        "id": "met2",
        "code": "MET2",
        "name": "Metode",
        "accent": "#7c3aed",
        "priority": 2,
        "stage": "mvp_gap",
        "lead": "Metode, statistikk, hypotesetesting, konfidensintervall og regresjon.",
        "sourceSummary": "Lokale sensorveiledninger og metodeoppskrifter finnes; faget trenger strukturert import.",
        "defaultHref": "../met2/",
        "flashcardsHref": "../flashcards/?subject=met2"
      },
      {
        "id": "bed1",
        "code": "BED1",
        "name": "Bedriftsøkonomi",
        "accent": "#20b97a",
        "priority": 2,
        "stage": "mvp_gap",
        "lead": "Kalkyler, resultat, investering, budsjettering og eksamenstrening.",
        "sourceSummary": "Lokale forelesninger, gruppeøvinger, Excel-filer og eksamensnært materiale finnes.",
        "defaultHref": "../bed1/",
        "flashcardsHref": "../flashcards/?subject=bed1"
      },
      {
        "id": "sam2",
        "code": "SAM2",
        "name": "Mikroøkonomi",
        "accent": "#f09828",
        "priority": 3,
        "stage": "structured_seed",
        "lead": "Konsumentteori, produsentteori, markedsteori, markedsmakt og strategi.",
        "sourceSummary": "Memoar, oppgaveprioritering og noe lokalt materiale er klart; flere kort og regnequiz mangler.",
        "defaultHref": "../sam2/",
        "flashcardsHref": "../sam2/oppgaver-klikkbar/"
      },
      {
        "id": "sam1a",
        "code": "SAM1A",
        "name": "Mikroøkonomi intro",
        "accent": "#f09828",
        "priority": 3,
        "stage": "structured_seed",
        "lead": "Markedslikevekt, elastisitet, velferd, markedssvikt og læringsmål.",
        "sourceSummary": "Kompendium og eksamensfiler er funnet og bør bli første kort- og oppgavepakke.",
        "defaultHref": "../sam1a/",
        "flashcardsHref": "../flashcards/?subject=sam1a"
      },
      {
        "id": "met1",
        "code": "MET1",
        "name": "Matematikk for økonomer",
        "accent": "#06b6d4",
        "priority": 3,
        "stage": "structured_seed",
        "lead": "Rente, nåverdi, annuitet, rekker og økonomisk matematikk.",
        "sourceSummary": "NNV- og renteoppgaver finnes lokalt og kan bli regnedrill med fasitkontroll.",
        "defaultHref": "../met1/",
        "flashcardsHref": "../flashcards/?subject=met1"
      },
      {
        "id": "kom1",
        "code": "KOM1",
        "name": "Kommunikasjon",
        "accent": "#e8bc68",
        "priority": 3,
        "stage": "structured_seed",
        "lead": "Rapportstruktur, presentasjon, akademisk språk og refleksjon.",
        "sourceSummary": "Innleveringer, presentasjoner og datasett finnes og bør bli skrivekort og maler.",
        "defaultHref": "../kom1/",
        "flashcardsHref": "../flashcards/?subject=kom1"
      },
      {
        "id": "ret1a",
        "code": "RET1A",
        "name": "Juridiske emner",
        "accent": "#3b82f6",
        "priority": 3,
        "stage": "structured_seed",
        "lead": "Avtalerett, selskapsrett, pengekrav og juridisk metode.",
        "sourceSummary": "Forelesninger, manduksjon og øvingsfiler finnes og bør bli disposisjonskort.",
        "defaultHref": "../ret1a/",
        "flashcardsHref": "../flashcards/?subject=ret1a"
      }
    ],
    "sources": [
      {
        "id": "ret14-exams",
        "subject": "RET14",
        "title": "RET14 eksamener og sensorveiledninger",
        "type": "exam_archive",
        "sourcePath": "Studier/NHH/RET14 Skatterett/Eksamensoppgaver og sensorveiledninger",
        "term": "2012-2025",
        "topics": [
          "fradrag",
          "aksjer",
          "personinntekt",
          "tidfesting",
          "formue"
        ],
        "rights": "local_private_source",
        "status": "ready_for_metadata",
        "suggestedUse": "Eksamensradar, A-besvarelser, caseoppgaver og sensorbaserte sjekklister"
      },
      {
        "id": "ret14-lectures",
        "subject": "RET14",
        "title": "RET14 forelesninger Canvas",
        "type": "lecture_pack",
        "sourcePath": "Studier/NHH/RET14 Skatterett/Forelesninger Canvas",
        "term": "2025",
        "topics": [
          "fradrag",
          "foretaksmodellen",
          "formuesskatt",
          "mva"
        ],
        "rights": "local_private_source",
        "status": "ready_for_metadata",
        "suggestedUse": "Lovkart, adaptive kort og hjemmelsbaserte flytdiagrammer"
      },
      {
        "id": "sol1-notes",
        "subject": "SOL1",
        "title": "SOL1 forelesningsnotater",
        "type": "notes",
        "sourcePath": "Studier/NHH/SOL1 Psykologi og ledelse/forelesningsnotater_sol1_v2.docx",
        "term": "2026",
        "topics": [
          "beslutning",
          "motivasjon",
          "team",
          "ledelse",
          "case"
        ],
        "rights": "owned_notes",
        "status": "ready_for_cards",
        "suggestedUse": "Kort, quizspørsmål, teoriskrivingsmaler og casekoblinger"
      },
      {
        "id": "sol1-exam-pack",
        "subject": "SOL1",
        "title": "SOL1 eksamen, sensor og A-besvarelse",
        "type": "exam_pack",
        "sourcePath": "Studier/NHH/SOL1 Psykologi og ledelse/course_files_export-*",
        "term": "V25-V26",
        "topics": [
          "case",
          "teoridel",
          "sensorblikk"
        ],
        "rights": "local_private_source",
        "status": "needs_publish_review",
        "suggestedUse": "Interaktiv eksamensflyt og eksempelsvar etter egen besvarelse"
      },
      {
        "id": "sam3-canvas",
        "subject": "SAM3",
        "title": "SAM3 Canvas-eksport",
        "type": "canvas_export",
        "sourcePath": "Studier/NHH/SAM3 Makroøkonomi/SAM3- canvas",
        "term": "2020-2026",
        "topics": [
          "solow",
          "is-mp",
          "as-ad",
          "phillips",
          "apen-okonomi"
        ],
        "rights": "local_private_source",
        "status": "ready_for_metadata",
        "suggestedUse": "Modellbygger, eksamensmodus, formelark og sensorbaserte oppgaver"
      },
      {
        "id": "sam3-v26-pack",
        "subject": "SAM3",
        "title": "SAM3 V26 eksamenspakke",
        "type": "exam_pack",
        "sourcePath": "sam3/eksamenspakker/v26",
        "term": "V26",
        "topics": [
          "eksamen",
          "a-besvarelse",
          "sensorveiledning"
        ],
        "rights": "app_packaged_protected_metadata",
        "status": "published_metadata",
        "suggestedUse": "Eksamensflyt: løs selv, sammenlign med A, sjekk sensor"
      },
      {
        "id": "mat10-canvas",
        "subject": "MAT10",
        "title": "MAT10 Canvas-eksport",
        "type": "canvas_export",
        "sourcePath": "Studier/NHH/MAT10/MAT10-V26-Analyse-og-line-r-algebra-*/viewer/files",
        "term": "V26",
        "topics": [
          "derivasjon",
          "integrasjon",
          "matriser",
          "taylor",
          "sensor"
        ],
        "rights": "local_private_source",
        "status": "ready_for_import",
        "suggestedUse": "Formelbank, regneoppgaver, sensorstyrt eksamensradar og oppgavegenerator"
      },
      {
        "id": "met2-downloads",
        "subject": "MET2",
        "title": "MET2 sensorveiledninger og metodeoppskrifter",
        "type": "exam_archive",
        "sourcePath": "Downloads/EksamenMET2*Sensorveiledning.pdf + P-verdi oppskrift MET2.pdf",
        "term": "H22-V25",
        "topics": [
          "hypotesetest",
          "konfidensintervall",
          "regresjon",
          "p-verdi"
        ],
        "rights": "local_private_source",
        "status": "ready_for_import",
        "suggestedUse": "Testvalg-quiz, regresjonslab og eksamensnære sjekklister"
      },
      {
        "id": "bed1-materials",
        "subject": "BED1",
        "title": "BED1A forelesninger, oppgaver og regneark",
        "type": "mixed_materials",
        "sourcePath": "Studier/NHH/BED1A",
        "term": "H25",
        "topics": [
          "produktkalkulasjon",
          "investering",
          "budsjettering",
          "resultat"
        ],
        "rights": "local_private_source",
        "status": "ready_for_import",
        "suggestedUse": "Kalkyledrill, Excel-baserte fasiter og scenariooppgaver"
      },
      {
        "id": "sam2-memo",
        "subject": "SAM2",
        "title": "SAM2 memoar",
        "type": "memo",
        "sourcePath": "Downloads/SAM2 memoar.docx",
        "term": "V26",
        "topics": [
          "arbeidsmåte",
          "konsumentteori",
          "oppgavebok",
          "eksamen"
        ],
        "rights": "owned_notes",
        "status": "published",
        "suggestedUse": "Førstegangs-onboarding og anbefalt arbeidsmåte"
      },
      {
        "id": "sam1a-materials",
        "subject": "SAM1A",
        "title": "SAM1A kompendium og eksamener",
        "type": "mixed_materials",
        "sourcePath": "Studier/NHH/SAM1A",
        "term": "H24-H25",
        "topics": [
          "markedslikevekt",
          "elastisitet",
          "velferd",
          "markedssvikt"
        ],
        "rights": "local_private_source",
        "status": "ready_for_import",
        "suggestedUse": "Læringsmål-kort, modellkort og grunnleggende oppgavebank"
      },
      {
        "id": "met1-materials",
        "subject": "MET1",
        "title": "MET1 NNV og rente",
        "type": "exercise_pack",
        "sourcePath": "Studier/NHH/MET1/MET1 NNV, og rente oppgaver.pdf",
        "term": "V25",
        "topics": [
          "naverdi",
          "annuitet",
          "effektiv-rente",
          "rekker"
        ],
        "rights": "local_private_source",
        "status": "ready_for_import",
        "suggestedUse": "Regnedrill, formelvalg og automatisk fasitkontroll"
      },
      {
        "id": "kom1-materials",
        "subject": "KOM1",
        "title": "KOM1 rapporter og presentasjoner",
        "type": "assignment_pack",
        "sourcePath": "Studier/NHH/KOM1",
        "term": "H25",
        "topics": [
          "problemstilling",
          "analyseavsnitt",
          "presentasjon",
          "sprak"
        ],
        "rights": "owned_assignments",
        "status": "ready_for_import",
        "suggestedUse": "Skrivekort, rapportmaler og muntlig presentasjonsdrill"
      },
      {
        "id": "ret1a-materials",
        "subject": "RET1A",
        "title": "RET1A forelesninger og eksamensoving",
        "type": "mixed_materials",
        "sourcePath": "Studier/NHH/RET1A",
        "term": "H25",
        "topics": [
          "juridisk-metode",
          "avtalerett",
          "pengekrav",
          "selskapsrett"
        ],
        "rights": "local_private_source",
        "status": "ready_for_import",
        "suggestedUse": "Disposisjonskort, vilkårskort og juridisk metodebank"
      }
    ],
    "decks": {
      "sam2": [
        {
          "id": "sam2-platform-modellvalg",
          "title": "SAM2 modellvalg og figurer",
          "status": "generated_seed",
          "sourceIds": [
            "sam2-memo"
          ],
          "cards": [
            {
              "q": "Hva bør du gjøre først i en SAM2-oppgave?",
              "a": "Identifiser modelltype: konsument, produsent, marked, velferd, monopol eller strategi. Tegn deretter figur før du regner.",
              "topic": "modellvalg",
              "tag": "Arbeidsmåte",
              "source": "SAM2 memoar"
            },
            {
              "q": "Hvorfor skal oppgaveboken prioriteres i SAM2?",
              "a": "Foreleser peker på oppgaveboken som viktigste eksamensgrunnlag. Fortløpende arbeid gir modellgjenkjenning og bedre eksamensspråk.",
              "topic": "eksamen",
              "tag": "Arbeidsmåte",
              "source": "SAM2 memoar"
            }
          ]
        }
      ],
      "met2": [
        {
          "id": "met2-platform-testflyt",
          "title": "MET2 testflyt og tolkning",
          "status": "generated_seed",
          "sourceIds": [
            "met2-downloads"
          ],
          "cards": [
            {
              "q": "Hva er minimumsflyten i en hypotesetest?",
              "a": "Formuler H0/H1, velg test, beregn testobservator eller p-verdi, sammenlign med signifikansnivå og konkluder i kontekst.",
              "topic": "hypotesetest",
              "tag": "Testflyt",
              "source": "MET2 sensorveiledninger"
            },
            {
              "q": "Hva må en god regresjonstolkning inneholde?",
              "a": "Koeffisientens fortegn, størrelse, enhet, alt-annet-likt-tolkning, usikkerhet og om resultatet er statistisk signifikant.",
              "topic": "regresjon",
              "tag": "Tolkning",
              "source": "MET2 sensorveiledninger"
            }
          ]
        }
      ],
      "mat10": [
        {
          "id": "mat10-platform-formelvalg",
          "title": "MAT10 formelvalg",
          "status": "generated_seed",
          "sourceIds": [
            "mat10-canvas"
          ],
          "cards": [
            {
              "q": "Hva er første sjekk i en optimeringsoppgave?",
              "a": "Finn definisjonsområdet, deriver, finn kritiske punkt, sjekk randpunkter og sammenlign funksjonsverdier.",
              "topic": "optimering",
              "tag": "Metode",
              "source": "MAT10 Canvas-eksport"
            },
            {
              "q": "Når er substitusjon et godt integrasjonsgrep?",
              "a": "Når uttrykket inneholder en indre funksjon og en faktor som ligner den deriverte av denne funksjonen.",
              "topic": "integrasjon",
              "tag": "Metode",
              "source": "MAT10 Canvas-eksport"
            }
          ]
        }
      ],
      "bed1": [
        {
          "id": "bed1-platform-kalkyle",
          "title": "BED1 kalkylebeslutninger",
          "status": "generated_seed",
          "sourceIds": [
            "bed1-materials"
          ],
          "cards": [
            {
              "q": "Hva avgjor om en kostnad er relevant i en beslutning?",
              "a": "Kostnaden må være fremtidig og forskjellig mellom alternativene. Historiske kostnader er normalt irrelevante.",
              "topic": "beslutning",
              "tag": "Kalkyle",
              "source": "BED1A forelesninger"
            },
            {
              "q": "Hvordan prioriterer du produkter ved knapp faktor?",
              "a": "Beregn dekningsbidrag per enhet av den knappe faktoren, og prioriter produktet med høyest bidrag per knapp faktor.",
              "topic": "produktkalkulasjon",
              "tag": "Kalkyle",
              "source": "BED1A oppgaver"
            }
          ]
        }
      ]
    },
    "questions": [
      {
        "id": "platform-ret14-source-audit",
        "subject": "RET14",
        "title": "Kilde til lovhjemmel",
        "source": "RET14 forelesninger Canvas",
        "topic": "Juridisk metode",
        "difficulty": "Middels",
        "minutes": 15,
        "exam": true,
        "prompt": "Velg et fradragstema og skriv hvilken hovedregel, spesialregel og eventuell unntaksregel som styrer drøftelsen.",
        "checklist": [
          "Start med hjemmel",
          "Skill hovedregel og unntak",
          "Knytt faktum til vilkår"
        ]
      },
      {
        "id": "platform-sam3-v26-flow",
        "subject": "SAM3",
        "title": "V26 eksamensflyt",
        "source": "SAM3 V26 eksamenspakke",
        "topic": "Eksamen",
        "difficulty": "Vanskelig",
        "minutes": 90,
        "exam": true,
        "prompt": "Løs én deloppgave fra V26 uten fasit, sammenlign deretter med A-besvarelse og merk tre konkrete forbedringspunkter fra sensorveiledningen.",
        "checklist": [
          "Løs før du leser fasit",
          "Sammenlign struktur og modellvalg",
          "Skriv tre neste steg"
        ]
      },
      {
        "id": "platform-mat10-sensor-pattern",
        "subject": "MAT10",
        "title": "Sensorstyrt metodevalg",
        "source": "MAT10 Canvas-eksport",
        "topic": "Metodevalg",
        "difficulty": "Middels",
        "minutes": 25,
        "exam": true,
        "prompt": "Velg en sensorveiledning og identifiser hvilke mellomregninger som faktisk gir poeng.",
        "checklist": [
          "Finn oppgavetype",
          "Noter metodegrep",
          "Lag ett kort fra poengkriteriet"
        ]
      },
      {
        "id": "platform-met2-testvalg",
        "subject": "MET2",
        "title": "Velg riktig test",
        "source": "MET2 sensorveiledninger",
        "topic": "Hypotesetest",
        "difficulty": "Middels",
        "minutes": 20,
        "exam": true,
        "prompt": "Les en oppgavetekst og begrunn testvalg ut fra datatype, parameter, antakelser og formulering av H1.",
        "checklist": [
          "Identifiser parameter",
          "Velg test",
          "Begrunn med data og antakelser"
        ]
      }
    ],
    "examAnalyses": {
      "ret14": {
        "code": "RET14",
        "name": "Skatterett",
        "summary": "RET14 prioriteres etter hvor ofte temaet kombinerer hjemmel, subsumsjon og beregning.",
        "topics": [
          [
            "Fradrag",
            "Oppofrelse, tilknytning og spesialregler.",
            "Høy",
            10,
            "Ja"
          ],
          [
            "Aksjer og fritaksmetode",
            "Subjekt, objekt, EØS/lavskattland og 3 %-regelen.",
            "Høy",
            9,
            "Ja"
          ],
          [
            "Personinntekt",
            "Klassifisering, virksomhet og beregning.",
            "Høy",
            8,
            "Ja"
          ]
        ]
      },
      "sam3": {
        "code": "SAM3",
        "name": "Makroøkonomi",
        "summary": "SAM3 prioriterer modellvalg og mekanismer som går igjen i eksamenspakker.",
        "topics": [
          [
            "IS-MP",
            "Etterspørselssjokk, rente og produksjon.",
            "Høy",
            9,
            "Ja"
          ],
          [
            "AS-AD",
            "Kort og lang sikt ved sjokk.",
            "Høy",
            8,
            "Ja"
          ],
          [
            "Åpen økonomi",
            "Valuta, UIP og kapitalmobilitet.",
            "Middels",
            6,
            "Delvis"
          ]
        ]
      },
      "mat10": {
        "code": "MAT10",
        "name": "Matematikk",
        "summary": "MAT10 prioriterer metoder som sensorveiledningene gjentar på tvers av eksamener.",
        "topics": [
          [
            "Derivasjon og optimering",
            "Kritiske punkt, randpunkter og økonomisk tolkning.",
            "Høy",
            9,
            "Ja"
          ],
          [
            "Integrasjon",
            "Substitusjon, delvis integrasjon og areal.",
            "Høy",
            8,
            "Ja"
          ],
          [
            "Lineær algebra",
            "Matriser, invers og lineære systemer.",
            "Høy",
            7,
            "Ja"
          ]
        ]
      },
      "met2": {
        "code": "MET2",
        "name": "Metode",
        "summary": "MET2 prioriterer presis tolkning, testvalg og regresjonsspråk.",
        "topics": [
          [
            "Hypotesetesting",
            "H0/H1, testobservator, p-verdi og konklusjon.",
            "Høy",
            9,
            "Ja"
          ],
          [
            "Konfidensintervall",
            "Tolkning og kobling til tester.",
            "Høy",
            8,
            "Ja"
          ],
          [
            "Regresjon",
            "Koeffisienter, standardfeil og forklaringskraft.",
            "Høy",
            7,
            "Ja"
          ]
        ]
      }
    },
    "formulaItems": {
      "mat10": [
        [
          "Derivasjon",
          "Produkt-, kvotient- og kjerneregel med kontroll av definisjonsområde.",
          "MAT10"
        ],
        [
          "Integrasjon",
          "Standardintegraler, substitusjon og delvis integrasjon.",
          "MAT10"
        ],
        [
          "Matriser",
          "Determinant, invers, rang og løsning av lineære systemer.",
          "MAT10"
        ]
      ],
      "met2": [
        [
          "Testobservator",
          "Z, t, andel, differanse og beslutningsregel.",
          "MET2"
        ],
        [
          "Konfidensintervall",
          "Estimat ± kritisk verdi × standardfeil.",
          "MET2"
        ],
        [
          "Regresjon",
          "Koeffisient, standardfeil, t-verdi, p-verdi og R2.",
          "MET2"
        ]
      ],
      "bed1": [
        [
          "Dekningsbidrag",
          "Pris minus variable kostnader; total DB og DB-grad.",
          "BED1"
        ],
        [
          "Selvkost",
          "Direkte kostnader pluss fordelte indirekte kostnader.",
          "BED1"
        ],
        [
          "Nåverdi",
          "Diskonter kontantstrømmer og trekk fra investering.",
          "BED1"
        ]
      ]
    },
    "learningPaths": {
      "ret14": [
        {
          "title": "1. Lovkart",
          "detail": "Start med hjemmel, vilkår og unntak.",
          "duration": "20 min",
          "kind": "oversikt"
        },
        {
          "title": "2. Adaptive kort",
          "detail": "Repeter feiltemaer med flere kort.",
          "duration": "25 min",
          "kind": "kort"
        },
        {
          "title": "3. Eksamenscase",
          "detail": "Skriv kort subsumsjon mot sensorpunkt.",
          "duration": "45 min",
          "kind": "eksamen"
        }
      ],
      "sam3": [
        {
          "title": "1. Modellvalg",
          "detail": "Velg Solow, IS-MP, AS-AD eller åpen økonomi.",
          "duration": "15 min",
          "kind": "oversikt"
        },
        {
          "title": "2. Formelquiz",
          "detail": "Lås symboler og sammenhenger.",
          "duration": "15 min",
          "kind": "formel"
        },
        {
          "title": "3. Eksamensflyt",
          "detail": "Løs, sammenlign med A, sjekk sensor.",
          "duration": "90 min",
          "kind": "eksamen"
        }
      ],
      "mat10": [
        {
          "title": "1. Formelbank",
          "detail": "Velg regel og vilkår før regning.",
          "duration": "15 min",
          "kind": "formel"
        },
        {
          "title": "2. Regnedrill",
          "detail": "Tren på én oppgavetype om gangen.",
          "duration": "30 min",
          "kind": "oppgave"
        },
        {
          "title": "3. Sensorpoeng",
          "detail": "Sammenlign egen mellomregning med sensor.",
          "duration": "25 min",
          "kind": "eksamen"
        }
      ],
      "met2": [
        {
          "title": "1. Begrep",
          "detail": "Lås p-verdi, KI og testobservator.",
          "duration": "20 min",
          "kind": "kort"
        },
        {
          "title": "2. Testvalg",
          "detail": "Begrunn metode fra oppgavetekst.",
          "duration": "25 min",
          "kind": "oppgave"
        },
        {
          "title": "3. Regresjon",
          "detail": "Tolk output og konkluder i kontekst.",
          "duration": "35 min",
          "kind": "oppgave"
        }
      ],
      "bed1": [
        {
          "title": "1. Begrep",
          "detail": "Skill kostnadstyper og kalkylemetoder.",
          "duration": "15 min",
          "kind": "kort"
        },
        {
          "title": "2. Regneoppsett",
          "detail": "Sett opp tabell før detaljregning.",
          "duration": "35 min",
          "kind": "oppgave"
        },
        {
          "title": "3. Beslutning",
          "detail": "Skriv anbefaling og økonomisk begrunnelse.",
          "duration": "20 min",
          "kind": "eksamen"
        }
      ],
      "sam2": [
        {
          "title": "1. Memoar",
          "detail": "Forstå hvorfor faget føles tungt først.",
          "duration": "8 min",
          "kind": "memo"
        },
        {
          "title": "2. Figur",
          "detail": "Tegn modellen før regning.",
          "duration": "20 min",
          "kind": "oppgave"
        },
        {
          "title": "3. Radar",
          "detail": "Koble oppgaven til eksamensprioritet.",
          "duration": "10 min",
          "kind": "eksamen"
        }
      ],
      "sam1a": [
        {
          "title": "1. Læringsmål",
          "detail": "Oversett hvert læringsmål til ett kontrollspørsmål.",
          "duration": "20 min",
          "kind": "oversikt"
        },
        {
          "title": "2. Modellkort",
          "detail": "Tegn markedskryss, elastisitet og velferd før oppgaver.",
          "duration": "25 min",
          "kind": "kort"
        },
        {
          "title": "3. Oppgave",
          "detail": "Løs en grunnkursoppgave med figur og kort tolkning.",
          "duration": "30 min",
          "kind": "oppgave"
        }
      ],
      "met1": [
        {
          "title": "1. Tidslinje",
          "detail": "Plasser kontantstrømmer før du velger formel.",
          "duration": "10 min",
          "kind": "oversikt"
        },
        {
          "title": "2. Formelvalg",
          "detail": "Skill nåverdi, sluttverdi, annuitet og effektiv rente.",
          "duration": "20 min",
          "kind": "formel"
        },
        {
          "title": "3. Regnedrill",
          "detail": "Løs korte NNV- og renteoppgaver med fasitkontroll.",
          "duration": "30 min",
          "kind": "oppgave"
        }
      ],
      "kom1": [
        {
          "title": "1. Disposisjon",
          "detail": "Lag problemstilling og avsnittsrekkefølge før skriving.",
          "duration": "20 min",
          "kind": "oversikt"
        },
        {
          "title": "2. Analyseavsnitt",
          "detail": "Tren på påstand, belegg, forklaring og kobling.",
          "duration": "25 min",
          "kind": "oppgave"
        },
        {
          "title": "3. Leveringssjekk",
          "detail": "Stram inn språk, overganger, kilder og konklusjon.",
          "duration": "15 min",
          "kind": "refleksjon"
        }
      ],
      "ret1a": [
        {
          "title": "1. Rettsregel",
          "detail": "Finn hjemmel, vilkår og unntak før faktum.",
          "duration": "20 min",
          "kind": "oversikt"
        },
        {
          "title": "2. Subsumsjon",
          "detail": "Bruk konkrete fakta mot hvert vilkår.",
          "duration": "30 min",
          "kind": "oppgave"
        },
        {
          "title": "3. Konklusjon",
          "detail": "Skriv korte delkonklusjoner og samlet svar.",
          "duration": "10 min",
          "kind": "eksamen"
        }
      ]
    },
    "memos": {
      "ret14": {
        "intro": "RET14 handler om å finne riktig hjemmel, strukturere vilkårene og bruke faktum presist.",
        "exam": "Eksamen belønner kort og presis rettsanvendelse med tydelige delkonklusjoner og ryddige beregninger.",
        "studyAdvice": "Start med lovkartet, bruk kort på hjemler og avslutt med gamle eksamenscase."
      },
      "subj_sol1": {
        "intro": "SOL1 handler om å forklare teori presist og bruke den aktivt på case.",
        "exam": "Eksamen skiller sterke svar på relevant teorivalg, casekobling og tydelig drøfting.",
        "studyAdvice": "Bruk begrepskort først, skriv korte teorisvar og sammenlign med A-besvarelser etter eget forsøk."
      },
      "sam3": {
        "intro": "SAM3 handler om å velge riktig makromodell og forklare mekanismen rolig.",
        "exam": "Eksamen belønner modellvalg, skiftforklaring og kobling til politikk eller åpen økonomi.",
        "studyAdvice": "Start med modellkort, lås formler med quiz og bruk V26-pakken som eksamensflyt."
      },
      "mat10": {
        "intro": "MAT10 blir lettere når du kjenner igjen oppgavetype før du regner.",
        "exam": "Sensor gir ofte poeng for metodevalg, ryddig mellomregning og kontroll av svar.",
        "studyAdvice": "Bruk formelbank som start, tren korte regneøkter og noter hvilke mellomsteg sensor faktisk belønner."
      },
      "met2": {
        "intro": "MET2 krever både riktig statistisk metode og presist språk.",
        "exam": "Eksamen belønner testvalg, korrekt tolkning av p-verdi/KI og tydelige regresjonskonklusjoner.",
        "studyAdvice": "Drill begrep først, løs testvalgoppgaver, og avslutt med output-tolkning."
      },
      "bed1": {
        "intro": "BED1 handler om å sette opp tall ryddig og forklare økonomisk beslutning.",
        "exam": "Eksamenspoeng kommer ofte fra standardoppsett, riktig kostnadsbegrep og kort anbefaling.",
        "studyAdvice": "Start med kalkylekort, gjør regnedrill og sammenlign oppsett mot gamle eksamener."
      },
      "sam2": {
        "intro": "SAM2 kan føles abstrakt i starten, særlig konsumentteorien, men blir lettere når modellene gjentas.",
        "exam": "Eksamen bygger tungt på oppgaveboken og krever figur, modellvalg og økonomisk språk.",
        "studyAdvice": "Gjør oppgaver fortløpende, tegn før du regner og bruk radaren til å prioritere."
      },
      "sam1a": {
        "intro": "SAM1A er grunnmuren i mikro: marked, elastisitet, velferd og markedssvikt forklart med enkle modeller.",
        "exam": "Eksamen krever ofte at figur, begrep og kort forklaring henger sammen i samme svar.",
        "studyAdvice": "Begynn med læringsmålene, tren på standardskift i figurer, og bruk hurtigkort for å låse begrepene."
      },
      "met1": {
        "intro": "MET1 handler om rente, nåverdi, annuitet og økonomisk matematikk der tid og kontantstrøm må holdes ryddig.",
        "exam": "Eksamen tester typisk formelvalg, periodeforståelse og evnen til å konkludere fra tallene.",
        "studyAdvice": "Start med rente- og NNV-kort, og bruk formelark som sjekkliste før lengre regneoppgaver."
      },
      "kom1": {
        "intro": "KOM1 samler rapportskriving, presentasjon og akademisk kommunikasjon til praktiske skrivegrep.",
        "exam": "Vurderingen handler ofte om struktur, presisjon, refleksjon og tydelig kobling mellom problemstilling og argumentasjon.",
        "studyAdvice": "Bruk siden som skriveverksted: bygg disposisjon, øv på analyseavsnitt og repeter overganger før levering."
      },
      "ret1a": {
        "intro": "RET1A handler om juridisk metode i praksis: finne rettsregel, drøfte vilkår og bruke faktum presist.",
        "exam": "Eksamen belønner ryddig struktur, tydelige delkonklusjoner og konkret subsumsjon fremfor lange generelle utlegninger.",
        "studyAdvice": "Tren først på metodekortene, deretter på gamle oppgaver med samme faste drøftingsmal."
      }
    },
    "recommendations": {
      "RET14": {
        "title": "RET14: Fradrag med hjemmel",
        "sub": "Lovkart og case",
        "cards": 28,
        "minutes": 35,
        "href": "../flashcards/?subject=ret14"
      },
      "SOL1": {
        "title": "SOL1: Teori til case",
        "sub": "MARS, motivasjon og team",
        "cards": 32,
        "minutes": 30,
        "href": "../flashcards/?subject=subj_sol1"
      },
      "SAM3": {
        "title": "SAM3: V26 eksamensflyt",
        "sub": "Løs, sammenlign, sjekk sensor",
        "cards": 0,
        "minutes": 90,
        "href": "../user/a-besvarelser.html#/sam3/v26"
      },
      "MAT10": {
        "title": "MAT10: Formelvalg først",
        "sub": "Sensorstyrt regnedrill",
        "cards": 12,
        "minutes": 30,
        "href": "../flashcards/?subject=mat10"
      },
      "MET2": {
        "title": "MET2: Testvalg og p-verdi",
        "sub": "Metodepresisjon",
        "cards": 12,
        "minutes": 25,
        "href": "../flashcards/?subject=met2"
      },
      "BED1": {
        "title": "BED1: Kalkylebeslutning",
        "sub": "DB, selvkost og NNV",
        "cards": 12,
        "minutes": 30,
        "href": "../flashcards/?subject=bed1"
      },
      "SAM2": {
        "title": "SAM2: Start med memoar",
        "sub": "Arbeidsmåte før oppgaver",
        "cards": 2,
        "minutes": 8,
        "href": "../sam2/memoar/"
      }
    }
  },
  "aliases": {
    "ret14": "ret14",
    "RET14": "ret14",
    "subj_sol1": "subj_sol1",
    "SOL1": "subj_sol1",
    "sol1": "subj_sol1",
    "sam3": "sam3",
    "SAM3": "sam3",
    "mat10": "mat10",
    "MAT10": "mat10",
    "met2": "met2",
    "MET2": "met2",
    "bed1": "bed1",
    "BED1": "bed1",
    "sam2": "sam2",
    "SAM2": "sam2",
    "sam1a": "sam1a",
    "SAM1A": "sam1a",
    "met1": "met1",
    "MET1": "met1",
    "kom1": "kom1",
    "KOM1": "kom1",
    "ret1a": "ret1a",
    "RET1A": "ret1a"
  }
};
  var data = payload.data;
  var aliases = payload.aliases;

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function code(value) {
    return String(value || '').toUpperCase().replace(/[\s_-]+/g, '');
  }

  function aliasKey(value) {
    return String(value || '').trim().toLowerCase().replace(/[\s-]+/g, '_');
  }

  function key(value) {
    var raw = String(value || '').trim();
    return aliases[raw] || aliases[aliasKey(raw)] || aliases[code(raw)] || aliasKey(raw);
  }

  function subjectFor(value) {
    var wanted = key(value);
    return data.subjects.find(function (subject) { return subject.id === wanted; }) || null;
  }

  function subjectCode(value) {
    var subject = subjectFor(value);
    return subject ? subject.code : code(value);
  }

  function sourceSubjectKey(source) {
    return key(source.subject);
  }

  function sourcesFor(value) {
    var wanted = key(value);
    return clone(data.sources.filter(function (source) { return sourceSubjectKey(source) === wanted; }));
  }

  function decksFor(value) {
    var wanted = key(value);
    var direct = data.decks[wanted] || data.decks[aliasKey(value)] || [];
    return clone(direct);
  }

  function questionsFor(value) {
    if (!value) return clone(data.questions);
    var wanted = key(value);
    return clone(data.questions.filter(function (question) { return key(question.subject) === wanted; }));
  }

  function keyedLookup(map, value) {
    var wanted = key(value);
    return map[wanted] || map[aliasKey(value)] || map[subjectCode(value)] || null;
  }

  function analysisFor(value) {
    return clone(keyedLookup(data.examAnalyses, value));
  }

  function formulaItemsFor(value) {
    return clone(keyedLookup(data.formulaItems, value) || []);
  }

  function learningPathFor(value) {
    return clone(keyedLookup(data.learningPaths, value) || []);
  }

  function memoFor(value) {
    var subject = subjectFor(value);
    var memo = keyedLookup(data.memos, value);
    if (memo) return clone(memo);
    if (!subject) return null;
    return {
      intro: subject.lead,
      exam: 'Faget bruker samme fagsidemal: oversikt, begrep eller formel, oppgaver, eksamensflyt og refleksjon.',
      studyAdvice: 'Start med memo og læringssti, ta en kort økt, og bruk neste anbefalte steg for å holde progresjonen i gang.'
    };
  }

  function recommendationFor(value) {
    var subject = subjectFor(value);
    var recommendation = keyedLookup(data.recommendations, value);
    if (recommendation) return clone(recommendation);
    if (!subject) return null;
    return { title: subject.code + ': første økt', sub: 'Anbefalt start', cards: 10, minutes: 20, href: subject.flashcardsHref };
  }

  function notes() {
    return Object.keys(data.memos).map(function (memoKey) {
      var subject = subjectFor(memoKey);
      var memo = data.memos[memoKey];
      return {
        id: 'memo-' + key(memoKey),
        title: (subject ? subject.code : subjectCode(memoKey)) + ' memo',
        subject: subject ? subject.code : subjectCode(memoKey),
        tags: 'memo, arbeidsmate',
        body: memo.intro + '\n\n' + memo.studyAdvice
      };
    });
  }

  function percentFromTopic(topic, fallback) {
    var score = Number(topic && topic[3]);
    if (Number.isFinite(score) && score > 0) return Math.max(45, Math.min(95, Math.round(score * 10))) + '%';
    return fallback || '68%';
  }

  function topicsForPage(subject) {
    var analysis = analysisFor(subject.id);
    if (analysis && analysis.topics && analysis.topics.length) {
      return analysis.topics.slice(0, 4).map(function (topic, index) {
        return [topic[0], topic[1] || topic[2] || 'Prioritert tema', percentFromTopic(topic, ['84%', '74%', '66%', '58%'][index])];
      });
    }
    var seen = {};
    var sourceTopics = [];
    sourcesFor(subject.id).forEach(function (source) {
      (source.topics || []).forEach(function (topic) {
        if (seen[topic]) return;
        seen[topic] = true;
        sourceTopics.push([topic, 'Bygges fra lokalt kildegrunnlag', sourceTopics.length === 0 ? '72%' : sourceTopics.length === 1 ? '64%' : '56%']);
      });
    });
    return sourceTopics.slice(0, 4);
  }

  function toolsForPage(subject) {
    return [
      ['▦', 'Fagmemo', 'Kort arbeidsmåte, eksamensform og beste start for faget.', 'Start', '#memo', subject.accent],
      ['✓', 'Flashcards', 'Korte kort fra katalogen og eksisterende fagpakker.', 'Kort', subject.flashcardsHref, subject.accent],
      ['▣', 'Oppgavebank', 'Eksamensnære oppgaver filtrert på fag og tema.', 'Oppgaver', '../user/oppgavebank.html?subject=' + encodeURIComponent(subject.code), '#2f62ff'],
      ['◈', 'Eksamensradar', 'Prioriter tema etter kilder, sensor og tidligere eksamen.', 'Radar', '#eksamensradar', '#e8bc68']
    ];
  }

  function sourceRowsForPage(subject) {
    return sourcesFor(subject.id).slice(0, 5).map(function (source) {
      return [source.title, source.suggestedUse];
    });
  }

  function canvasRowsForPage(subject) {
    return sourcesFor(subject.id).slice(0, 5).map(function (source) {
      return [source.title, source.sourcePath + ' · ' + source.status, source.type];
    });
  }

  function practiceForPage(subject) {
    var decks = decksFor(subject.id);
    var cards = [];
    decks.forEach(function (deck) {
      (deck.cards || []).forEach(function (card) {
        if (cards.length >= 3) return;
        cards.push([card.tag || card.topic, card.q, 'Kilde: ' + card.source, card.a, card.topic || 'Svar kort og presist.']);
      });
    });
    if (!cards.length) return null;
    return { label: 'Kildekort', intro: 'Hurtigkort laget fra den felles læringskatalogen.', cards: cards };
  }

  function checklistForPage(subject) {
    var question = questionsFor(subject.id)[0];
    if (!question || !question.checklist) return [];
    return question.checklist.map(function (item, index) {
      return [index === 0 ? 'Start' : index === 1 ? 'Metode' : 'Svar', item, question.topic];
    });
  }

  function pageFor(value) {
    var subject = subjectFor(value);
    if (!subject) return null;
    var sources = sourcesFor(subject.id);
    var decks = decksFor(subject.id);
    var cards = decks.reduce(function (sum, deck) { return sum + (deck.cards || []).length; }, 0);
    var analysis = analysisFor(subject.id);
    var path = learningPathFor(subject.id);
    return {
      id: subject.id,
      code: subject.code,
      name: subject.name,
      kicker: subject.stage === 'rich' ? 'Plattformklar fagpakke' : subject.stage === 'mvp_gap' ? 'MVP-løft' : 'Strukturert fagmal',
      accent: subject.accent,
      progress: subject.stage === 'rich' ? '62%' : subject.stage === 'ready_for_import' ? '42%' : subject.stage === 'mvp_gap' ? '34%' : '28%',
      lead: subject.lead,
      stats: [[String(sources.length), 'kilder'], [String(cards || decks.length), cards ? 'kort fra katalogen' : 'kortpakker'], [subject.stage === 'rich' ? 'Aktiv' : 'Bygges', 'plattform']],
      tools: toolsForPage(subject),
      topics: topicsForPage(subject),
      plan: (path.length ? path : [
        { title: '1. Oversikt', detail: 'Les memo og se kildegrunnlag.', duration: '10 min' },
        { title: '2. Kort', detail: 'Ta første kortøkt.', duration: '20 min' },
        { title: '3. Oppgave', detail: 'Løs en eksamensnær oppgave.', duration: '30 min' }
      ]).map(function (step) { return [step.title, step.detail, step.duration]; }),
      sources: sourceRowsForPage(subject),
      canvasMaterials: canvasRowsForPage(subject),
      formulaSheet: formulaItemsFor(subject.id),
      memo: memoFor(subject.id),
      examRadar: analysis ? {
        label: 'Kildebasert prioritet',
        summary: analysis.summary,
        accent: subject.accent,
        rows: analysis.topics.map(function (topic, index) {
          return [topic[0], topic[1], percentFromTopic(topic, ['86%', '76%', '66%', '58%'][index])];
        })
      } : null,
      practice: practiceForPage(subject),
      examChecklist: checklistForPage(subject),
      next: recommendationFor(subject.id).title
    };
  }

  window.HaugnesLearningContent = {
    version: data.version,
    updatedAt: data.updatedAt,
    subjects: clone(data.subjects),
    sources: clone(data.sources),
    decks: clone(data.decks),
    questions: clone(data.questions),
    examAnalyses: clone(data.examAnalyses),
    formulaItems: clone(data.formulaItems),
    learningPaths: clone(data.learningPaths),
    memos: clone(data.memos),
    recommendations: clone(data.recommendations),
    clone: clone,
    code: code,
    key: key,
    bySubject: function (items, value) {
      var wanted = key(value);
      return clone((items || []).filter(function (item) { return key(item.subject) === wanted; }));
    },
    getSubject: function (value) { return clone(subjectFor(value)); },
    sourcesFor: sourcesFor,
    decksFor: decksFor,
    allQuestions: function () { return clone(data.questions); },
    questionsFor: questionsFor,
    analysisFor: analysisFor,
    formulaItemsFor: formulaItemsFor,
    learningPathFor: learningPathFor,
    memoFor: memoFor,
    recommendationFor: recommendationFor,
    notes: function () { return clone(notes()); },
    pageFor: pageFor
  };
})(window);
